import type { BankEntry } from "@/lib/question-bank/types";

// A2 — simple sentences on familiar topics: family, home, routine, likes.
// Mostly present tense; a simple past on very familiar events is fine.
export const A2: BankEntry[] = [
  {
    id: "a2-family-01",
    domain: "family",
    text: {
      en: "Tell me about your family.",
      fr: "Parlez-moi de votre famille.",
      "nl-BE": "Vertel eens over uw familie.",
      es: "Hábleme de su familia.",
      it: "Mi parli della sua famiglia.",
      de: "Erzählen Sie mir von Ihrer Familie.",
    },
  },
  {
    id: "a2-family-02",
    domain: "family",
    text: {
      en: "Tell me about a good friend.",
      fr: "Parlez-moi d'un bon ami ou d'une bonne amie.",
      "nl-BE": "Vertel eens over een goede vriend of vriendin.",
      es: "Hábleme de un buen amigo o una buena amiga.",
      it: "Mi parli di un buon amico o di una buona amica.",
      de: "Erzählen Sie mir von einem guten Freund oder einer guten Freundin.",
    },
  },
  {
    id: "a2-home-01",
    domain: "home_city",
    text: {
      en: "Describe your home.",
      fr: "Décrivez votre logement.",
      "nl-BE": "Beschrijf uw woning.",
      es: "Describa su casa.",
      it: "Descriva la sua casa.",
      de: "Beschreiben Sie Ihre Wohnung oder Ihr Haus.",
    },
  },
  {
    id: "a2-home-02",
    domain: "home_city",
    text: {
      en: "Describe the room you are in right now.",
      fr: "Décrivez la pièce où vous êtes en ce moment.",
      "nl-BE": "Beschrijf de kamer waar u nu bent.",
      es: "Describa la habitación donde está ahora mismo.",
      it: "Descriva la stanza in cui si trova adesso.",
      de: "Beschreiben Sie den Raum, in dem Sie gerade sind.",
    },
  },
  {
    id: "a2-home-03",
    domain: "home_city",
    text: {
      en: "Tell me about the town or city where you live.",
      fr: "Parlez-moi de la ville ou du village où vous habitez.",
      "nl-BE": "Vertel eens over de stad of het dorp waar u woont.",
      es: "Hábleme de la ciudad o del pueblo donde vive.",
      it: "Mi parli della città o del paese in cui abita.",
      de: "Erzählen Sie mir von der Stadt oder dem Dorf, wo Sie wohnen.",
    },
  },
  {
    id: "a2-hobbies-01",
    domain: "hobbies_free_time",
    text: {
      en: "What do you like to do at the weekend?",
      fr: "Qu'est-ce que vous aimez faire le week-end ?",
      "nl-BE": "Wat doet u graag in het weekend?",
      es: "¿Qué le gusta hacer los fines de semana?",
      it: "Che cosa le piace fare nel fine settimana?",
      de: "Was machen Sie gern am Wochenende?",
    },
  },
  {
    id: "a2-hobbies-02",
    domain: "hobbies_free_time",
    text: {
      en: "Tell me about your hobbies.",
      fr: "Parlez-moi de vos loisirs.",
      "nl-BE": "Vertel eens over uw hobby's.",
      es: "Hábleme de sus aficiones.",
      it: "Mi parli dei suoi hobby.",
      de: "Erzählen Sie mir von Ihren Hobbys.",
    },
  },
  {
    id: "a2-hobbies-03",
    domain: "hobbies_free_time",
    text: {
      en: "What music do you like, and when do you listen to it?",
      fr: "Quelle musique aimez-vous, et quand est-ce que vous l'écoutez ?",
      "nl-BE": "Naar welke muziek luistert u graag, en wanneer?",
      es: "¿Qué música le gusta, y cuándo la escucha?",
      it: "Che musica le piace, e quando la ascolta?",
      de: "Welche Musik mögen Sie, und wann hören Sie sie?",
    },
  },
  {
    id: "a2-hobbies-04",
    domain: "hobbies_free_time",
    text: {
      en: "What do you do to relax after work or school?",
      fr: "Que faites-vous pour vous détendre après le travail ou les cours ?",
      "nl-BE": "Wat doet u om te ontspannen na het werk of na school?",
      es: "¿Qué hace para relajarse después del trabajo o de las clases?",
      it: "Che cosa fa per rilassarsi dopo il lavoro o la scuola?",
      de: "Was machen Sie, um sich nach der Arbeit oder der Schule zu entspannen?",
    },
  },
  {
    id: "a2-hobbies-05",
    domain: "hobbies_free_time",
    text: {
      en: "What kind of films or series do you like?",
      fr: "Quel genre de films ou de séries aimez-vous ?",
      "nl-BE": "Van welk soort films of series houdt u?",
      es: "¿Qué tipo de películas o series le gustan?",
      it: "Che genere di film o di serie le piace?",
      de: "Welche Art von Filmen oder Serien mögen Sie?",
    },
  },
  {
    id: "a2-food-01",
    domain: "food_daily_life",
    text: {
      en: "What do you usually do in the morning?",
      fr: "Que faites-vous d'habitude le matin ?",
      "nl-BE": "Wat doet u meestal 's morgens?",
      es: "¿Qué suele hacer por la mañana?",
      it: "Che cosa fa di solito la mattina?",
      de: "Was machen Sie normalerweise am Morgen?",
    },
  },
  {
    id: "a2-food-02",
    domain: "food_daily_life",
    text: {
      en: "What does a normal day look like for you?",
      fr: "Comment se passe une journée normale pour vous ?",
      "nl-BE": "Hoe ziet een gewone dag er voor u uit?",
      es: "¿Cómo es un día normal para usted?",
      it: "Com'è una giornata normale per lei?",
      de: "Wie sieht ein normaler Tag für Sie aus?",
    },
  },
  {
    id: "a2-work-01",
    domain: "work_studies",
    text: {
      en: "How do you go to work or school, and how long does it take?",
      fr: "Comment allez-vous au travail ou en cours, et combien de temps ça prend ?",
      "nl-BE": "Hoe gaat u naar uw werk of naar school, en hoe lang duurt dat?",
      es: "¿Cómo va al trabajo o a clase, y cuánto tiempo tarda?",
      it: "Come va al lavoro o a scuola, e quanto tempo ci mette?",
      de: "Wie kommen Sie zur Arbeit oder zur Schule, und wie lange brauchen Sie?",
    },
  },
  {
    id: "a2-other-01",
    domain: "opinions_other",
    text: {
      en: "What do you like to buy when you go shopping?",
      fr: "Qu'est-ce que vous aimez acheter quand vous faites les magasins ?",
      "nl-BE": "Wat koopt u graag als u gaat winkelen?",
      es: "¿Qué le gusta comprar cuando va de compras?",
      it: "Che cosa le piace comprare quando va a fare shopping?",
      de: "Was kaufen Sie gern, wenn Sie einkaufen gehen?",
    },
  },
  {
    id: "a2-other-02",
    domain: "opinions_other",
    text: {
      en: "How do you feel today, and why?",
      fr: "Comment vous sentez-vous aujourd'hui, et pourquoi ?",
      "nl-BE": "Hoe voelt u zich vandaag, en waarom?",
      es: "¿Cómo se siente hoy, y por qué?",
      it: "Come si sente oggi, e perché?",
      de: "Wie fühlen Sie sich heute, und warum?",
    },
  },
  {
    id: "a2-travel-01",
    domain: "travel",
    text: {
      en: "Where did you go on your last holiday? What did you do there?",
      fr: "Où êtes-vous allé pendant vos dernières vacances ? Qu'avez-vous fait là-bas ?",
      "nl-BE": "Waar was u op uw laatste vakantie? Wat hebt u daar gedaan?",
      es: "¿Adónde fue en sus últimas vacaciones? ¿Qué hizo allí?",
      it: "Dove è andato nelle ultime vacanze? Che cosa ha fatto lì?",
      de: "Wo waren Sie im letzten Urlaub? Was haben Sie dort gemacht?",
    },
  },
  {
    id: "a2-tech-01",
    domain: "technology",
    text: {
      en: "When do you use your phone during the day, and for what?",
      fr: "Quand utilisez-vous votre téléphone pendant la journée, et pour quoi faire ?",
      "nl-BE": "Wanneer gebruikt u uw gsm tijdens de dag, en waarvoor?",
      es: "¿Cuándo usa el móvil durante el día, y para qué?",
      it: "Quando usa il telefono durante la giornata, e per fare che cosa?",
      de: "Wann benutzen Sie Ihr Handy am Tag, und wofür?",
    },
  },
];
