import type { BankEntry } from "@/lib/question-bank/types";

// B1 — descriptions, simple opinions, past and future, familiar topics
// developed over a few sentences.
export const B1: BankEntry[] = [
  {
    id: "b1-food-01",
    domain: "food_daily_life",
    text: {
      en: "Describe a typical day in your life.",
      fr: "Décrivez une journée typique de votre vie.",
      "nl-BE": "Beschrijf een typische dag uit uw leven.",
      es: "Describa un día típico de su vida.",
      it: "Descriva una giornata tipica della sua vita.",
      de: "Beschreiben Sie einen typischen Tag in Ihrem Leben.",
    },
  },
  {
    id: "b1-food-02",
    domain: "food_daily_life",
    text: {
      en: "Tell me about your favourite restaurant and what makes it special.",
      fr: "Parlez-moi de votre restaurant préféré et de ce qui le rend spécial.",
      "nl-BE": "Vertel eens over uw favoriete restaurant en wat het bijzonder maakt.",
      es: "Hábleme de su restaurante favorito y de lo que lo hace especial.",
      it: "Mi parli del suo ristorante preferito e di che cosa lo rende speciale.",
      de: "Erzählen Sie mir von Ihrem Lieblingsrestaurant und was es besonders macht.",
    },
  },
  {
    id: "b1-hobbies-01",
    domain: "hobbies_free_time",
    text: {
      en: "What are your plans for next weekend?",
      fr: "Quels sont vos projets pour le week-end prochain ?",
      "nl-BE": "Wat zijn uw plannen voor volgend weekend?",
      es: "¿Qué planes tiene para el próximo fin de semana?",
      it: "Che programmi ha per il prossimo fine settimana?",
      de: "Was haben Sie am nächsten Wochenende vor?",
    },
  },
  {
    id: "b1-hobbies-02",
    domain: "hobbies_free_time",
    text: {
      en: "Tell me in more detail about a sport or hobby you enjoy.",
      fr: "Parlez-moi plus en détail d'un sport ou d'un loisir que vous aimez.",
      "nl-BE": "Vertel eens wat uitgebreider over een sport of hobby die u leuk vindt.",
      es: "Hábleme con más detalle de un deporte o una afición que le guste.",
      it: "Mi parli più nel dettaglio di uno sport o di un hobby che le piace.",
      de: "Erzählen Sie mir genauer von einem Sport oder Hobby, das Ihnen Spaß macht.",
    },
  },
  {
    id: "b1-hobbies-03",
    domain: "hobbies_free_time",
    text: {
      en: "Tell me about a book or a film you liked, and why.",
      fr: "Parlez-moi d'un livre ou d'un film que vous avez aimé, et pourquoi.",
      "nl-BE": "Vertel eens over een boek of een film die u goed vond, en waarom.",
      es: "Hábleme de un libro o una película que le gustó, y por qué.",
      it: "Mi parli di un libro o di un film che le è piaciuto, e perché.",
      de: "Erzählen Sie mir von einem Buch oder Film, der Ihnen gefallen hat, und warum.",
    },
  },
  {
    id: "b1-hobbies-04",
    domain: "hobbies_free_time",
    text: {
      en: "What do you usually do when you have a day off?",
      fr: "Que faites-vous d'habitude quand vous avez un jour de congé ?",
      "nl-BE": "Wat doet u meestal als u een vrije dag hebt?",
      es: "¿Qué suele hacer cuando tiene un día libre?",
      it: "Che cosa fa di solito quando ha un giorno libero?",
      de: "Was machen Sie normalerweise, wenn Sie einen freien Tag haben?",
    },
  },
  {
    id: "b1-home-01",
    domain: "home_city",
    text: {
      en: "What do you like about your town or your region?",
      fr: "Qu'est-ce que vous aimez dans votre ville ou votre région ?",
      "nl-BE": "Wat vindt u fijn aan uw stad of uw streek?",
      es: "¿Qué le gusta de su ciudad o de su región?",
      it: "Che cosa le piace della sua città o della sua regione?",
      de: "Was gefällt Ihnen an Ihrer Stadt oder Ihrer Region?",
    },
  },
  {
    id: "b1-family-01",
    domain: "family",
    text: {
      en: "Describe a tradition in your family.",
      fr: "Décrivez une tradition de votre famille.",
      "nl-BE": "Beschrijf een traditie in uw familie.",
      es: "Describa una tradición de su familia.",
      it: "Descriva una tradizione della sua famiglia.",
      de: "Beschreiben Sie eine Tradition in Ihrer Familie.",
    },
  },
  {
    id: "b1-family-02",
    domain: "family",
    text: {
      en: "Tell me about a celebration or a party you remember well.",
      fr: "Parlez-moi d'une fête ou d'une célébration dont vous vous souvenez bien.",
      "nl-BE": "Vertel eens over een feest dat u zich goed herinnert.",
      es: "Hábleme de una fiesta o una celebración que recuerde bien.",
      it: "Mi parli di una festa o di una celebrazione che ricorda bene.",
      de: "Erzählen Sie mir von einem Fest oder einer Feier, an die Sie sich gut erinnern.",
    },
  },
  {
    id: "b1-travel-01",
    domain: "travel",
    text: {
      en: "What kind of holidays do you like, and why?",
      fr: "Quel genre de vacances aimez-vous, et pourquoi ?",
      "nl-BE": "Wat voor vakanties vindt u leuk, en waarom?",
      es: "¿Qué tipo de vacaciones le gustan, y por qué?",
      it: "Che tipo di vacanze le piace, e perché?",
      de: "Welche Art von Urlaub mögen Sie, und warum?",
    },
  },
  {
    id: "b1-travel-02",
    domain: "travel",
    text: {
      en: "Tell me about the last trip you took.",
      fr: "Parlez-moi du dernier voyage que vous avez fait.",
      "nl-BE": "Vertel eens over de laatste reis die u gemaakt hebt.",
      es: "Hábleme del último viaje que hizo.",
      it: "Mi parli dell'ultimo viaggio che ha fatto.",
      de: "Erzählen Sie mir von Ihrer letzten Reise.",
    },
  },
  {
    id: "b1-work-01",
    domain: "work_studies",
    text: {
      en: "What do you like most about your job or your studies?",
      fr: "Qu'est-ce que vous aimez le plus dans votre travail ou vos études ?",
      "nl-BE": "Wat vindt u het leukst aan uw werk of uw studie?",
      es: "¿Qué es lo que más le gusta de su trabajo o de sus estudios?",
      it: "Che cosa le piace di più del suo lavoro o dei suoi studi?",
      de: "Was gefällt Ihnen an Ihrer Arbeit oder Ihrem Studium am meisten?",
    },
  },
  {
    id: "b1-work-02",
    domain: "work_studies",
    text: {
      en: "What is a skill you would like to improve, and why?",
      fr: "Quelle compétence aimeriez-vous améliorer, et pourquoi ?",
      "nl-BE": "Welke vaardigheid zou u graag verbeteren, en waarom?",
      es: "¿Qué habilidad le gustaría mejorar, y por qué?",
      it: "Quale capacità le piacerebbe migliorare, e perché?",
      de: "Welche Fähigkeit möchten Sie gern verbessern, und warum?",
    },
  },
  {
    id: "b1-tech-01",
    domain: "technology",
    text: {
      en: "How do you use the internet in your daily life?",
      fr: "Comment utilisez-vous Internet dans votre vie de tous les jours ?",
      "nl-BE": "Hoe gebruikt u het internet in uw dagelijks leven?",
      es: "¿Cómo usa internet en su vida diaria?",
      it: "Come usa internet nella vita di tutti i giorni?",
      de: "Wie nutzen Sie das Internet in Ihrem Alltag?",
    },
  },
  {
    id: "b1-other-01",
    domain: "opinions_other",
    text: {
      en: "Describe a perfect day for you.",
      fr: "Décrivez une journée parfaite pour vous.",
      "nl-BE": "Beschrijf een perfecte dag voor u.",
      es: "Describa un día perfecto para usted.",
      it: "Descriva una giornata perfetta per lei.",
      de: "Beschreiben Sie einen perfekten Tag für Sie.",
    },
  },
  {
    id: "b1-other-02",
    domain: "opinions_other",
    text: {
      en: "What makes you happy in your daily life?",
      fr: "Qu'est-ce qui vous rend heureux dans votre vie de tous les jours ?",
      "nl-BE": "Waar wordt u gelukkig van in uw dagelijks leven?",
      es: "¿Qué le hace feliz en su vida diaria?",
      it: "Che cosa la rende felice nella vita di tutti i giorni?",
      de: "Was macht Sie in Ihrem Alltag glücklich?",
    },
  },
  {
    id: "b1-other-03",
    domain: "opinions_other",
    text: {
      en: "Tell me about something you are looking forward to.",
      fr: "Parlez-moi de quelque chose que vous attendez avec impatience.",
      "nl-BE": "Vertel eens over iets waar u naar uitkijkt.",
      es: "Hábleme de algo que espera con ilusión.",
      it: "Mi parli di qualcosa che aspetta con impazienza.",
      de: "Erzählen Sie mir von etwas, auf das Sie sich freuen.",
    },
  },
];
