import type { BankEntry } from "@/lib/question-bank/types";

// B2 — narrate experience, compare, explain and justify a personal view,
// simple hypotheticals about the speaker's own life. Still personal: no
// for/against debate, no role-play, no specialist knowledge (Track AA-02).
export const B2: BankEntry[] = [
  {
    id: "b2-family-01",
    domain: "family",
    text: {
      en: "Describe a happy memory from your childhood.",
      fr: "Décrivez un souvenir heureux de votre enfance.",
      "nl-BE": "Beschrijf een gelukkige herinnering uit uw kindertijd.",
      es: "Describa un recuerdo feliz de su infancia.",
      it: "Descriva un ricordo felice della sua infanzia.",
      de: "Beschreiben Sie eine schöne Erinnerung aus Ihrer Kindheit.",
    },
  },
  {
    id: "b2-travel-01",
    domain: "travel",
    text: {
      en: "If you could visit any place in the world, where would you go, and why?",
      fr: "Si vous pouviez visiter n'importe quel endroit du monde, où iriez-vous, et pourquoi ?",
      "nl-BE": "Als u eender welke plek ter wereld kon bezoeken, waar zou u naartoe gaan, en waarom?",
      es: "Si pudiera visitar cualquier lugar del mundo, ¿adónde iría, y por qué?",
      it: "Se potesse visitare qualsiasi posto al mondo, dove andrebbe, e perché?",
      de: "Wenn Sie jeden Ort der Welt besuchen könnten, wohin würden Sie reisen, und warum?",
    },
  },
  {
    id: "b2-travel-02",
    domain: "travel",
    text: {
      en: "Tell me about a trip you will always remember.",
      fr: "Parlez-moi d'un voyage dont vous vous souviendrez toujours.",
      "nl-BE": "Vertel eens over een reis die u nooit zult vergeten.",
      es: "Hábleme de un viaje que siempre recordará.",
      it: "Mi parli di un viaggio che ricorderà sempre.",
      de: "Erzählen Sie mir von einer Reise, an die Sie sich immer erinnern werden.",
    },
  },
  {
    id: "b2-work-01",
    domain: "work_studies",
    text: {
      en: "Tell me about a difficulty you have overcome recently.",
      fr: "Parlez-moi d'une difficulté que vous avez surmontée récemment.",
      "nl-BE": "Vertel eens over een moeilijkheid die u onlangs overwonnen hebt.",
      es: "Hábleme de una dificultad que haya superado recientemente.",
      it: "Mi parli di una difficoltà che ha superato di recente.",
      de: "Erzählen Sie mir von einer Schwierigkeit, die Sie vor Kurzem überwunden haben.",
    },
  },
  {
    id: "b2-work-02",
    domain: "work_studies",
    text: {
      en: "What are your goals for the next five years?",
      fr: "Quels sont vos objectifs pour les cinq prochaines années ?",
      "nl-BE": "Wat zijn uw doelen voor de komende vijf jaar?",
      es: "¿Cuáles son sus objetivos para los próximos cinco años?",
      it: "Quali sono i suoi obiettivi per i prossimi cinque anni?",
      de: "Welche Ziele haben Sie für die nächsten fünf Jahre?",
    },
  },
  {
    id: "b2-work-03",
    domain: "work_studies",
    text: {
      en: "Tell me about a time when you had to make a difficult decision.",
      fr: "Parlez-moi d'un moment où vous avez dû prendre une décision difficile.",
      "nl-BE": "Vertel eens over een moment waarop u een moeilijke beslissing moest nemen.",
      es: "Hábleme de un momento en que tuvo que tomar una decisión difícil.",
      it: "Mi parli di una volta in cui ha dovuto prendere una decisione difficile.",
      de: "Erzählen Sie mir von einer Situation, in der Sie eine schwierige Entscheidung treffen mussten.",
    },
  },
  {
    id: "b2-work-04",
    domain: "work_studies",
    text: {
      en: "Describe a situation where you had to adapt quickly.",
      fr: "Décrivez une situation où vous avez dû vous adapter rapidement.",
      "nl-BE": "Beschrijf een situatie waarin u zich snel moest aanpassen.",
      es: "Describa una situación en la que tuvo que adaptarse rápidamente.",
      it: "Descriva una situazione in cui ha dovuto adattarsi rapidamente.",
      de: "Beschreiben Sie eine Situation, in der Sie sich schnell anpassen mussten.",
    },
  },
  {
    id: "b2-home-01",
    domain: "home_city",
    text: {
      en: "If you could change one thing about the town where you live, what would it be, and why?",
      fr: "Si vous pouviez changer une chose dans la ville où vous habitez, que choisiriez-vous, et pourquoi ?",
      "nl-BE": "Als u één ding kon veranderen aan de stad waar u woont, wat zou dat zijn, en waarom?",
      es: "Si pudiera cambiar una cosa de la ciudad donde vive, ¿qué sería, y por qué?",
      it: "Se potesse cambiare una cosa della città in cui abita, che cosa sceglierebbe, e perché?",
      de: "Wenn Sie eine Sache an Ihrem Wohnort ändern könnten, was wäre das, und warum?",
    },
  },
  {
    id: "b2-home-02",
    domain: "home_city",
    text: {
      en: "What would your ideal home look like?",
      fr: "À quoi ressemblerait votre logement idéal ?",
      "nl-BE": "Hoe zou uw ideale woning eruitzien?",
      es: "¿Cómo sería su casa ideal?",
      it: "Come sarebbe la sua casa ideale?",
      de: "Wie würde Ihr ideales Zuhause aussehen?",
    },
  },
  {
    id: "b2-home-03",
    domain: "home_city",
    text: {
      en: "How do you think the place where you live will change in the next twenty years?",
      fr: "Comment pensez-vous que l'endroit où vous vivez va changer dans les vingt prochaines années ?",
      "nl-BE": "Hoe denkt u dat de plek waar u woont de komende twintig jaar zal veranderen?",
      es: "¿Cómo cree que cambiará el lugar donde vive en los próximos veinte años?",
      it: "Come pensa che cambierà il posto in cui vive nei prossimi vent'anni?",
      de: "Wie wird sich Ihr Wohnort Ihrer Meinung nach in den nächsten zwanzig Jahren verändern?",
    },
  },
  {
    id: "b2-hobbies-01",
    domain: "hobbies_free_time",
    text: {
      en: "What would you do if you had more free time?",
      fr: "Que feriez-vous si vous aviez plus de temps libre ?",
      "nl-BE": "Wat zou u doen als u meer vrije tijd had?",
      es: "¿Qué haría si tuviera más tiempo libre?",
      it: "Che cosa farebbe se avesse più tempo libero?",
      de: "Was würden Sie machen, wenn Sie mehr Freizeit hätten?",
    },
  },
  {
    id: "b2-hobbies-02",
    domain: "hobbies_free_time",
    text: {
      en: "Which new language would you like to learn, and why?",
      fr: "Quelle nouvelle langue aimeriez-vous apprendre, et pourquoi ?",
      "nl-BE": "Welke nieuwe taal zou u graag leren, en waarom?",
      es: "¿Qué nuevo idioma le gustaría aprender, y por qué?",
      it: "Quale nuova lingua le piacerebbe imparare, e perché?",
      de: "Welche neue Sprache würden Sie gern lernen, und warum?",
    },
  },
  {
    id: "b2-hobbies-03",
    domain: "hobbies_free_time",
    text: {
      en: "What is your favourite way to relax, and why does it work for you?",
      fr: "Quelle est votre façon préférée de vous détendre, et pourquoi est-ce que ça marche pour vous ?",
      "nl-BE": "Hoe ontspant u het liefst, en waarom werkt dat voor u?",
      es: "¿Cuál es su forma favorita de relajarse, y por qué le funciona?",
      it: "Qual è il suo modo preferito di rilassarsi, e perché funziona per lei?",
      de: "Wie entspannen Sie sich am liebsten, und warum funktioniert das für Sie?",
    },
  },
  {
    id: "b2-hobbies-04",
    domain: "hobbies_free_time",
    text: {
      en: "What skill would you most like to master, and how would you go about it?",
      fr: "Quelle compétence aimeriez-vous le plus maîtriser, et comment vous y prendriez-vous ?",
      "nl-BE": "Welke vaardigheid zou u het liefst beheersen, en hoe zou u dat aanpakken?",
      es: "¿Qué habilidad le gustaría dominar, y cómo lo haría?",
      it: "Quale capacità le piacerebbe di più padroneggiare, e come farebbe?",
      de: "Welche Fähigkeit würden Sie am liebsten beherrschen, und wie würden Sie das angehen?",
    },
  },
  {
    id: "b2-food-01",
    domain: "food_daily_life",
    text: {
      en: "Describe your ideal way to start the day.",
      fr: "Décrivez votre façon idéale de commencer la journée.",
      "nl-BE": "Beschrijf hoe u uw dag idealiter begint.",
      es: "Describa su manera ideal de empezar el día.",
      it: "Descriva il suo modo ideale di iniziare la giornata.",
      de: "Beschreiben Sie, wie Sie Ihren Tag am liebsten beginnen.",
    },
  },
  {
    id: "b2-tech-01",
    domain: "technology",
    text: {
      en: "How has technology changed the way you live or work?",
      fr: "Comment la technologie a-t-elle changé votre façon de vivre ou de travailler ?",
      "nl-BE": "Hoe heeft technologie uw manier van leven of werken veranderd?",
      es: "¿Cómo ha cambiado la tecnología su forma de vivir o de trabajar?",
      it: "Come ha cambiato la tecnologia il suo modo di vivere o di lavorare?",
      de: "Wie hat die Technik Ihre Art zu leben oder zu arbeiten verändert?",
    },
  },
  {
    id: "b2-tech-02",
    domain: "technology",
    text: {
      en: "What place do social media have in your life?",
      fr: "Quelle place les réseaux sociaux ont-ils dans votre vie ?",
      "nl-BE": "Welke plaats hebben sociale media in uw leven?",
      es: "¿Qué lugar ocupan las redes sociales en su vida?",
      it: "Che posto hanno i social network nella sua vita?",
      de: "Welche Rolle spielen soziale Medien in Ihrem Leben?",
    },
  },
  {
    id: "b2-other-01",
    domain: "opinions_other",
    text: {
      en: "What is the biggest difference between your life now and five years ago?",
      fr: "Quelle est la plus grande différence entre votre vie aujourd'hui et il y a cinq ans ?",
      "nl-BE": "Wat is het grootste verschil tussen uw leven nu en vijf jaar geleden?",
      es: "¿Cuál es la mayor diferencia entre su vida ahora y hace cinco años?",
      it: "Qual è la differenza più grande tra la sua vita di oggi e quella di cinque anni fa?",
      de: "Was ist der größte Unterschied zwischen Ihrem Leben heute und vor fünf Jahren?",
    },
  },
  {
    id: "b2-other-02",
    domain: "opinions_other",
    text: {
      en: "Tell me about a person you admire, and explain why.",
      fr: "Parlez-moi d'une personne que vous admirez, et expliquez pourquoi.",
      "nl-BE": "Vertel eens over iemand die u bewondert, en leg uit waarom.",
      es: "Hábleme de una persona a la que admira, y explique por qué.",
      it: "Mi parli di una persona che ammira, e spieghi perché.",
      de: "Erzählen Sie mir von einem Menschen, den Sie bewundern, und erklären Sie, warum.",
    },
  },
  {
    id: "b2-other-03",
    domain: "opinions_other",
    text: {
      en: "If you could live in a different period of history, which would you choose, and why?",
      fr: "Si vous pouviez vivre à une autre époque, laquelle choisiriez-vous, et pourquoi ?",
      "nl-BE": "Als u in een ander tijdperk kon leven, welk zou u kiezen, en waarom?",
      es: "Si pudiera vivir en otra época, ¿cuál elegiría, y por qué?",
      it: "Se potesse vivere in un'altra epoca, quale sceglierebbe, e perché?",
      de: "Wenn Sie in einer anderen Epoche leben könnten, welche würden Sie wählen, und warum?",
    },
  },
  {
    id: "b2-other-04",
    domain: "opinions_other",
    text: {
      en: "Tell me about a time you changed your mind about something important to you.",
      fr: "Parlez-moi d'un moment où vous avez changé d'avis sur quelque chose d'important pour vous.",
      "nl-BE": "Vertel eens over een moment waarop u van mening veranderde over iets wat belangrijk voor u was.",
      es: "Hábleme de un momento en que cambió de opinión sobre algo importante para usted.",
      it: "Mi parli di una volta in cui ha cambiato idea su qualcosa di importante per lei.",
      de: "Erzählen Sie mir von einem Moment, in dem Sie Ihre Meinung über etwas Wichtiges geändert haben.",
    },
  },
  {
    id: "b2-other-05",
    domain: "opinions_other",
    text: {
      en: "How do you deal with stress, and does it work?",
      fr: "Comment gérez-vous le stress, et est-ce que ça fonctionne ?",
      "nl-BE": "Hoe gaat u om met stress, en werkt dat?",
      es: "¿Cómo maneja el estrés, y le funciona?",
      it: "Come gestisce lo stress, e funziona?",
      de: "Wie gehen Sie mit Stress um, und funktioniert das?",
    },
  },
  {
    id: "b2-other-06",
    domain: "opinions_other",
    text: {
      en: "If you could have dinner with anyone, living or dead, who would it be, and why?",
      fr: "Si vous pouviez dîner avec n'importe qui, vivant ou disparu, qui choisiriez-vous, et pourquoi ?",
      "nl-BE": "Als u met eender wie kon gaan eten, levend of overleden, wie zou dat zijn, en waarom?",
      es: "Si pudiera cenar con cualquier persona, viva o fallecida, ¿quién sería, y por qué?",
      it: "Se potesse cenare con chiunque, vivo o scomparso, chi sceglierebbe, e perché?",
      de: "Wenn Sie mit irgendeinem Menschen essen gehen könnten, lebend oder verstorben, wer wäre das, und warum?",
    },
  },
  {
    id: "b2-other-07",
    domain: "opinions_other",
    text: {
      en: "What is something most people don't know about you?",
      fr: "Qu'est-ce que la plupart des gens ne savent pas sur vous ?",
      "nl-BE": "Wat weten de meeste mensen niet over u?",
      es: "¿Qué es algo que la mayoría de la gente no sabe de usted?",
      it: "Che cosa la maggior parte delle persone non sa di lei?",
      de: "Was wissen die meisten Menschen nicht über Sie?",
    },
  },
];
