import type { BankEntry } from "@/lib/question-bank/types";

// C1 — explain, compare and weigh things up, starting from the speaker's own
// life and experience (Track AA-02, after beta testers found free-written
// C1/C2 questions "DELF/DALF-like"). Rules for every entry:
//   - about the speaker's own experience or views, answerable by any adult;
//   - never for/against argumentation, never role-play ("convince…",
//     "justify to a doctor…"), never "argue the opposite";
//   - no specialist, factual or local knowledge needed.
// Difficulty comes from what a full answer needs (narration + explanation +
// comparison or reflection), not from an abstract or exam-style task.
// Code picks these (lib/question-bank/index.ts pickBankQuestion); the examiner
// asks one, then ONE of its followUps, then the next bank question.
export const C1: BankEntry[] = [
  {
    id: "c1-home-01",
    domain: "home_city",
    text: {
      en: "What would make you decide to leave the place where you live, and what would you miss most?",
      fr: "Qu'est-ce qui pourrait vous décider à quitter l'endroit où vous vivez, et qu'est-ce qui vous manquerait le plus ?",
      "nl-BE": "Wat zou u doen beslissen om te verhuizen van de plek waar u woont, en wat zou u het meest missen?",
      es: "¿Qué le haría decidir marcharse del lugar donde vive, y qué es lo que más echaría de menos?",
      it: "Che cosa potrebbe spingerla a lasciare il posto in cui vive, e che cosa le mancherebbe di più?",
      de: "Was würde Sie dazu bringen, Ihren Wohnort zu verlassen, und was würden Sie am meisten vermissen?",
    },
    simpler: {
      en: "Would you like to move one day? Why?",
      fr: "Vous aimeriez déménager un jour ? Pourquoi ?",
      "nl-BE": "Zou u ooit willen verhuizen? Waarom?",
      es: "¿Le gustaría mudarse algún día? ¿Por qué?",
      it: "Le piacerebbe traslocare un giorno? Perché?",
      de: "Möchten Sie eines Tages umziehen? Warum?",
    },
    followUps: [
      {
        en: "What would be the hardest part of leaving?",
        fr: "Qu'est-ce qui serait le plus difficile au moment de partir ?",
        "nl-BE": "Wat zou het moeilijkste zijn aan het vertrekken?",
        es: "¿Qué sería lo más difícil de irse?",
        it: "Che cosa sarebbe più difficile nel partire?",
        de: "Was wäre das Schwierigste daran, wegzugehen?",
      },
      {
        en: "Has your idea of home changed over the years?",
        fr: "Votre idée de ce qu'est un « chez-soi » a-t-elle changé avec les années ?",
        "nl-BE": "Is uw idee van 'thuis' in de loop der jaren veranderd?",
        es: "¿Ha cambiado con los años su idea de lo que es un hogar?",
        it: "La sua idea di « casa » è cambiata con gli anni?",
        de: "Hat sich Ihre Vorstellung von Zuhause im Lauf der Jahre verändert?",
      },
    ],
  },
  {
    id: "c1-home-02",
    domain: "home_city",
    text: {
      en: "How has the place where you grew up shaped the person you are today?",
      fr: "En quoi l'endroit où vous avez grandi a-t-il fait de vous la personne que vous êtes aujourd'hui ?",
      "nl-BE": "Hoe heeft de plek waar u opgroeide u gevormd tot wie u vandaag bent?",
      es: "¿De qué manera el lugar donde creció ha influido en la persona que es hoy?",
      it: "In che modo il posto in cui è cresciuto ha fatto di lei la persona che è oggi?",
      de: "Wie hat der Ort, an dem Sie aufgewachsen sind, Sie zu dem Menschen gemacht, der Sie heute sind?",
    },
    simpler: {
      en: "Where did you grow up? Did you like it there?",
      fr: "Où avez-vous grandi ? Vous aimiez cet endroit ?",
      "nl-BE": "Waar bent u opgegroeid? Vond u het daar fijn?",
      es: "¿Dónde creció? ¿Le gustaba ese lugar?",
      it: "Dove è cresciuto? Le piaceva quel posto?",
      de: "Wo sind Sie aufgewachsen? Hat es Ihnen dort gefallen?",
    },
    followUps: [
      {
        en: "Is there something from that place you still carry with you?",
        fr: "Y a-t-il quelque chose de cet endroit que vous gardez encore en vous ?",
        "nl-BE": "Is er iets van die plek dat u nog altijd met u meedraagt?",
        es: "¿Hay algo de ese lugar que todavía lleva consigo?",
        it: "C'è qualcosa di quel posto che porta ancora con sé?",
        de: "Gibt es etwas von diesem Ort, das Sie bis heute mit sich tragen?",
      },
      {
        en: "How is it different from where you live now?",
        fr: "En quoi est-ce différent de l'endroit où vous vivez maintenant ?",
        "nl-BE": "Wat is het verschil met de plek waar u nu woont?",
        es: "¿En qué se diferencia del lugar donde vive ahora?",
        it: "In che cosa è diverso dal posto in cui vive adesso?",
        de: "Worin unterscheidet er sich von dem Ort, an dem Sie jetzt leben?",
      },
    ],
  },
  {
    id: "c1-family-01",
    domain: "family",
    text: {
      en: "What is something your parents did that you would do differently, and why?",
      fr: "Qu'est-ce que vos parents faisaient que vous feriez différemment, et pourquoi ?",
      "nl-BE": "Wat deden uw ouders dat u anders zou doen, en waarom?",
      es: "¿Qué hacían sus padres que usted haría de otra manera, y por qué?",
      it: "Che cosa facevano i suoi genitori che lei farebbe diversamente, e perché?",
      de: "Was haben Ihre Eltern gemacht, das Sie anders machen würden, und warum?",
    },
    simpler: {
      en: "What did your parents teach you?",
      fr: "Qu'est-ce que vos parents vous ont appris ?",
      "nl-BE": "Wat hebben uw ouders u geleerd?",
      es: "¿Qué le enseñaron sus padres?",
      it: "Che cosa le hanno insegnato i suoi genitori?",
      de: "Was haben Ihre Eltern Ihnen beigebracht?",
    },
    followUps: [
      {
        en: "Did you understand their choice better later on?",
        fr: "Avez-vous mieux compris leur choix plus tard ?",
        "nl-BE": "Hebt u hun keuze later beter begrepen?",
        es: "¿Entendió mejor su decisión más adelante?",
        it: "Ha capito meglio la loro scelta più tardi?",
        de: "Haben Sie ihre Entscheidung später besser verstanden?",
      },
      {
        en: "How does that show in your life today?",
        fr: "Comment cela se voit-il dans votre vie aujourd'hui ?",
        "nl-BE": "Hoe merkt u dat vandaag in uw leven?",
        es: "¿Cómo se nota eso en su vida hoy?",
        it: "Come si vede questo nella sua vita di oggi?",
        de: "Woran merkt man das heute in Ihrem Leben?",
      },
    ],
  },
  {
    id: "c1-family-02",
    domain: "family",
    text: {
      en: "Tell me about someone in your life who changed the way you see things. How did they do it?",
      fr: "Parlez-moi de quelqu'un dans votre vie qui a changé votre façon de voir les choses. Comment s'y est-il pris ?",
      "nl-BE": "Vertel eens over iemand in uw leven die uw kijk op de dingen veranderd heeft. Hoe deed die persoon dat?",
      es: "Hábleme de alguien en su vida que cambió su manera de ver las cosas. ¿Cómo lo hizo?",
      it: "Mi parli di qualcuno nella sua vita che ha cambiato il suo modo di vedere le cose. Come ci è riuscito?",
      de: "Erzählen Sie mir von jemandem in Ihrem Leben, der Ihre Sicht auf die Dinge verändert hat. Wie hat er das geschafft?",
    },
    simpler: {
      en: "Who is an important person in your life? Why?",
      fr: "Qui est une personne importante dans votre vie ? Pourquoi ?",
      "nl-BE": "Wie is een belangrijke persoon in uw leven? Waarom?",
      es: "¿Quién es una persona importante en su vida? ¿Por qué?",
      it: "Chi è una persona importante nella sua vita? Perché?",
      de: "Wer ist ein wichtiger Mensch in Ihrem Leben? Warum?",
    },
    followUps: [
      {
        en: "What do you think you would be like without that person?",
        fr: "Comment pensez-vous que vous seriez sans cette personne ?",
        "nl-BE": "Hoe denkt u dat u zou zijn zonder die persoon?",
        es: "¿Cómo cree que sería usted sin esa persona?",
        it: "Come pensa che sarebbe senza quella persona?",
        de: "Wie wären Sie Ihrer Meinung nach ohne diesen Menschen?",
      },
      {
        en: "Did you realise it at the time, or only later?",
        fr: "Vous en êtes-vous rendu compte sur le moment, ou seulement plus tard ?",
        "nl-BE": "Besefte u dat op dat moment, of pas later?",
        es: "¿Se dio cuenta en ese momento, o solo más tarde?",
        it: "Se n'è reso conto in quel momento, o solo più tardi?",
        de: "Ist Ihnen das damals bewusst gewesen oder erst später?",
      },
    ],
  },
  {
    id: "c1-work-01",
    domain: "work_studies",
    text: {
      en: "Tell me about a choice in your studies or career that turned out differently than you expected. What would you do differently now?",
      fr: "Parlez-moi d'un choix d'études ou de carrière qui s'est passé autrement que prévu. Que feriez-vous différemment aujourd'hui ?",
      "nl-BE": "Vertel eens over een keuze in uw studie of loopbaan die anders uitdraaide dan verwacht. Wat zou u nu anders doen?",
      es: "Hábleme de una decisión sobre sus estudios o su carrera que salió de forma distinta a lo esperado. ¿Qué haría diferente ahora?",
      it: "Mi parli di una scelta di studi o di carriera che è andata diversamente dal previsto. Che cosa farebbe di diverso oggi?",
      de: "Erzählen Sie mir von einer Entscheidung in Studium oder Beruf, die anders ausgegangen ist als erwartet. Was würden Sie heute anders machen?",
    },
    simpler: {
      en: "How did you choose your job or your studies?",
      fr: "Comment avez-vous choisi votre travail ou vos études ?",
      "nl-BE": "Hoe hebt u uw werk of uw studie gekozen?",
      es: "¿Cómo eligió su trabajo o sus estudios?",
      it: "Come ha scelto il suo lavoro o i suoi studi?",
      de: "Wie haben Sie Ihren Beruf oder Ihr Studium gewählt?",
    },
    followUps: [
      {
        en: "What did that teach you about yourself?",
        fr: "Qu'est-ce que cela vous a appris sur vous-même ?",
        "nl-BE": "Wat hebt u daaruit over uzelf geleerd?",
        es: "¿Qué le enseñó eso sobre usted mismo?",
        it: "Che cosa le ha insegnato su sé stesso?",
        de: "Was haben Sie dabei über sich selbst gelernt?",
      },
      {
        en: "What would you tell someone facing the same choice?",
        fr: "Que diriez-vous à quelqu'un qui doit faire le même choix ?",
        "nl-BE": "Wat zou u zeggen tegen iemand die voor dezelfde keuze staat?",
        es: "¿Qué le diría a alguien que tiene que tomar la misma decisión?",
        it: "Che cosa direbbe a qualcuno che deve fare la stessa scelta?",
        de: "Was würden Sie jemandem sagen, der vor derselben Entscheidung steht?",
      },
    ],
  },
  {
    id: "c1-work-02",
    domain: "work_studies",
    text: {
      en: "Which part of your work or studies gives you real satisfaction, and which part do you find hardest to accept?",
      fr: "Quelle partie de votre travail ou de vos études vous apporte une vraie satisfaction, et laquelle avez-vous le plus de mal à accepter ?",
      "nl-BE": "Welk deel van uw werk of studie geeft u echte voldoening, en welk deel vindt u het moeilijkst om te aanvaarden?",
      es: "¿Qué parte de su trabajo o de sus estudios le da una verdadera satisfacción, y cuál le cuesta más aceptar?",
      it: "Quale parte del suo lavoro o dei suoi studi le dà una vera soddisfazione, e quale fa più fatica ad accettare?",
      de: "Welcher Teil Ihrer Arbeit oder Ihres Studiums gibt Ihnen echte Befriedigung, und womit können Sie sich am schwersten abfinden?",
    },
    simpler: {
      en: "What do you like and not like in your job or studies?",
      fr: "Qu'est-ce que vous aimez et n'aimez pas dans votre travail ou vos études ?",
      "nl-BE": "Wat vindt u leuk en niet leuk aan uw werk of studie?",
      es: "¿Qué le gusta y qué no le gusta de su trabajo o sus estudios?",
      it: "Che cosa le piace e che cosa non le piace del suo lavoro o dei suoi studi?",
      de: "Was mögen Sie an Ihrer Arbeit oder Ihrem Studium und was nicht?",
    },
    followUps: [
      {
        en: "Has that changed since you started?",
        fr: "Est-ce que cela a changé depuis vos débuts ?",
        "nl-BE": "Is dat veranderd sinds u begonnen bent?",
        es: "¿Ha cambiado eso desde que empezó?",
        it: "È cambiato qualcosa da quando ha iniziato?",
        de: "Hat sich das seit Ihrem Anfang verändert?",
      },
      {
        en: "How do you deal with the difficult part in practice?",
        fr: "Concrètement, comment faites-vous avec la partie difficile ?",
        "nl-BE": "Hoe gaat u in de praktijk om met het moeilijke deel?",
        es: "En la práctica, ¿cómo lleva la parte difícil?",
        it: "In pratica, come affronta la parte difficile?",
        de: "Wie gehen Sie im Alltag mit dem schwierigen Teil um?",
      },
    ],
  },
  {
    id: "c1-hobbies-01",
    domain: "hobbies_free_time",
    text: {
      en: "Tell me about an interest or activity that has stayed with you for years. What keeps you coming back to it?",
      fr: "Parlez-moi d'une passion ou d'une activité qui vous accompagne depuis des années. Qu'est-ce qui vous y ramène toujours ?",
      "nl-BE": "Vertel eens over een interesse of activiteit die u al jaren bijblijft. Wat trekt u er telkens weer naartoe?",
      es: "Hábleme de un interés o una actividad que le acompaña desde hace años. ¿Qué le hace volver siempre a ella?",
      it: "Mi parli di un interesse o di un'attività che la accompagna da anni. Che cosa la spinge a tornarci sempre?",
      de: "Erzählen Sie mir von einem Interesse oder einer Tätigkeit, die Sie seit Jahren begleitet. Was zieht Sie immer wieder dorthin zurück?",
    },
    simpler: {
      en: "What hobby have you had for a long time? Why do you like it?",
      fr: "Quel loisir avez-vous depuis longtemps ? Pourquoi l'aimez-vous ?",
      "nl-BE": "Welke hobby hebt u al lang? Waarom vindt u die leuk?",
      es: "¿Qué afición tiene desde hace mucho tiempo? ¿Por qué le gusta?",
      it: "Che hobby ha da tanto tempo? Perché le piace?",
      de: "Welches Hobby haben Sie schon lange? Warum mögen Sie es?",
    },
    followUps: [
      {
        en: "How has the way you do it changed over time?",
        fr: "Comment votre façon de la pratiquer a-t-elle évolué avec le temps ?",
        "nl-BE": "Hoe is de manier waarop u het doet in de loop der tijd veranderd?",
        es: "¿Cómo ha cambiado con el tiempo su manera de practicarla?",
        it: "Come è cambiato nel tempo il suo modo di praticarla?",
        de: "Wie hat sich die Art, wie Sie es machen, mit der Zeit verändert?",
      },
      {
        en: "What would be missing from your life without it?",
        fr: "Qu'est-ce qui manquerait à votre vie sans elle ?",
        "nl-BE": "Wat zou er in uw leven ontbreken zonder die activiteit?",
        es: "¿Qué le faltaría a su vida sin ella?",
        it: "Che cosa mancherebbe alla sua vita senza di essa?",
        de: "Was würde Ihnen ohne sie im Leben fehlen?",
      },
    ],
  },
  {
    id: "c1-hobbies-02",
    domain: "hobbies_free_time",
    text: {
      en: "Is there an activity you gave up — a sport, an instrument, a hobby — that you sometimes regret? Tell me about it.",
      fr: "Y a-t-il une activité que vous avez abandonnée — un sport, un instrument, un loisir — et que vous regrettez parfois ? Racontez-moi.",
      "nl-BE": "Is er een activiteit waarmee u gestopt bent — een sport, een instrument, een hobby — waar u soms spijt van hebt? Vertel eens.",
      es: "¿Hay alguna actividad que dejó — un deporte, un instrumento, una afición — y que a veces echa de menos? Cuénteme.",
      it: "C'è un'attività che ha abbandonato — uno sport, uno strumento, un hobby — e che a volte rimpiange? Me ne parli.",
      de: "Gibt es eine Tätigkeit, die Sie aufgegeben haben — einen Sport, ein Instrument, ein Hobby — und die Sie manchmal bereuen? Erzählen Sie mal.",
    },
    simpler: {
      en: "Did you stop a hobby? Why?",
      fr: "Avez-vous arrêté un loisir ? Pourquoi ?",
      "nl-BE": "Bent u ooit met een hobby gestopt? Waarom?",
      es: "¿Dejó alguna afición? ¿Por qué?",
      it: "Ha smesso un hobby? Perché?",
      de: "Haben Sie mit einem Hobby aufgehört? Warum?",
    },
    followUps: [
      {
        en: "What made you stop at the time?",
        fr: "Qu'est-ce qui vous a fait arrêter à l'époque ?",
        "nl-BE": "Waarom bent u er toen mee gestopt?",
        es: "¿Qué le hizo dejarlo en aquel momento?",
        it: "Che cosa l'ha portata a smettere allora?",
        de: "Warum haben Sie damals aufgehört?",
      },
      {
        en: "Would you start again today? What would be different?",
        fr: "Recommenceriez-vous aujourd'hui ? Qu'est-ce qui serait différent ?",
        "nl-BE": "Zou u er vandaag opnieuw mee beginnen? Wat zou er anders zijn?",
        es: "¿Volvería a empezar hoy? ¿Qué sería diferente?",
        it: "Ricomincerebbe oggi? Che cosa sarebbe diverso?",
        de: "Würden Sie heute wieder anfangen? Was wäre anders?",
      },
    ],
  },
  {
    id: "c1-food-01",
    domain: "food_daily_life",
    text: {
      en: "Which of your daily habits would you most like to change, and what has stopped you so far?",
      fr: "Quelle habitude de votre quotidien aimeriez-vous le plus changer, et qu'est-ce qui vous en a empêché jusqu'ici ?",
      "nl-BE": "Welke dagelijkse gewoonte zou u het liefst veranderen, en wat heeft u tot nu toe tegengehouden?",
      es: "¿Qué hábito de su día a día le gustaría más cambiar, y qué se lo ha impedido hasta ahora?",
      it: "Quale abitudine quotidiana le piacerebbe di più cambiare, e che cosa gliel'ha impedito finora?",
      de: "Welche Ihrer Alltagsgewohnheiten würden Sie am liebsten ändern, und was hat Sie bisher davon abgehalten?",
    },
    simpler: {
      en: "What habit would you like to change? Why?",
      fr: "Quelle habitude aimeriez-vous changer ? Pourquoi ?",
      "nl-BE": "Welke gewoonte zou u graag veranderen? Waarom?",
      es: "¿Qué costumbre le gustaría cambiar? ¿Por qué?",
      it: "Quale abitudine le piacerebbe cambiare? Perché?",
      de: "Welche Gewohnheit möchten Sie ändern? Warum?",
    },
    followUps: [
      {
        en: "What have you already tried?",
        fr: "Qu'avez-vous déjà essayé ?",
        "nl-BE": "Wat hebt u al geprobeerd?",
        es: "¿Qué ha intentado ya?",
        it: "Che cosa ha già provato?",
        de: "Was haben Sie schon versucht?",
      },
      {
        en: "What would be different in your life if you managed it?",
        fr: "Qu'est-ce qui changerait dans votre vie si vous y arriviez ?",
        "nl-BE": "Wat zou er in uw leven anders zijn als het u lukte?",
        es: "¿Qué cambiaría en su vida si lo consiguiera?",
        it: "Che cosa cambierebbe nella sua vita se ci riuscisse?",
        de: "Was wäre in Ihrem Leben anders, wenn Sie es schaffen würden?",
      },
    ],
  },
  {
    id: "c1-food-02",
    domain: "food_daily_life",
    text: {
      en: "How have your eating habits changed since you were a child, and why?",
      fr: "Comment vos habitudes alimentaires ont-elles changé depuis votre enfance, et pourquoi ?",
      "nl-BE": "Hoe zijn uw eetgewoonten veranderd sinds uw kindertijd, en waarom?",
      es: "¿Cómo han cambiado sus hábitos de alimentación desde su infancia, y por qué?",
      it: "Come sono cambiate le sue abitudini alimentari dall'infanzia a oggi, e perché?",
      de: "Wie haben sich Ihre Essgewohnheiten seit Ihrer Kindheit verändert, und warum?",
    },
    simpler: {
      en: "What did you eat as a child? Do you eat the same today?",
      fr: "Que mangiez-vous quand vous étiez enfant ? Vous mangez la même chose aujourd'hui ?",
      "nl-BE": "Wat at u als kind? Eet u vandaag nog hetzelfde?",
      es: "¿Qué comía de pequeño? ¿Come lo mismo hoy?",
      it: "Che cosa mangiava da bambino? Mangia le stesse cose oggi?",
      de: "Was haben Sie als Kind gegessen? Essen Sie heute noch dasselbe?",
    },
    followUps: [
      {
        en: "Which change are you happiest about?",
        fr: "De quel changement êtes-vous le plus content ?",
        "nl-BE": "Over welke verandering bent u het meest tevreden?",
        es: "¿De qué cambio está más contento?",
        it: "Di quale cambiamento è più contento?",
        de: "Über welche Veränderung sind Sie am glücklichsten?",
      },
      {
        en: "Is there a dish that takes you straight back to a particular moment?",
        fr: "Y a-t-il un plat qui vous ramène directement à un moment précis ?",
        "nl-BE": "Is er een gerecht dat u meteen terugbrengt naar een bepaald moment?",
        es: "¿Hay algún plato que le lleve directamente a un momento concreto?",
        it: "C'è un piatto che la riporta subito a un momento preciso?",
        de: "Gibt es ein Gericht, das Sie sofort an einen bestimmten Moment erinnert?",
      },
    ],
  },
  {
    id: "c1-travel-01",
    domain: "travel",
    text: {
      en: "Tell me about a place you visited that didn't match what you expected. What surprised you?",
      fr: "Parlez-moi d'un endroit que vous avez visité et qui ne correspondait pas à ce que vous imaginiez. Qu'est-ce qui vous a surpris ?",
      "nl-BE": "Vertel eens over een plek die u bezocht hebt en die niet was wat u verwachtte. Wat verraste u?",
      es: "Hábleme de un lugar que visitó y que no era como esperaba. ¿Qué le sorprendió?",
      it: "Mi parli di un posto che ha visitato e che non corrispondeva a quello che si aspettava. Che cosa l'ha sorpresa?",
      de: "Erzählen Sie mir von einem Ort, den Sie besucht haben und der anders war als erwartet. Was hat Sie überrascht?",
    },
    simpler: {
      en: "Did a trip ever surprise you? How?",
      fr: "Un voyage vous a-t-il déjà surpris ? Comment ?",
      "nl-BE": "Heeft een reis u ooit verrast? Hoe?",
      es: "¿Alguna vez le sorprendió un viaje? ¿Cómo?",
      it: "Un viaggio l'ha mai sorpresa? Come?",
      de: "Hat Sie eine Reise schon einmal überrascht? Wie?",
    },
    followUps: [
      {
        en: "Did it change the way you travel?",
        fr: "Est-ce que cela a changé votre façon de voyager ?",
        "nl-BE": "Heeft dat uw manier van reizen veranderd?",
        es: "¿Cambió eso su manera de viajar?",
        it: "Ha cambiato il suo modo di viaggiare?",
        de: "Hat das Ihre Art zu reisen verändert?",
      },
      {
        en: "What would you tell a friend who is going there?",
        fr: "Que diriez-vous à un ami qui part là-bas ?",
        "nl-BE": "Wat zou u zeggen tegen een vriend die ernaartoe gaat?",
        es: "¿Qué le diría a un amigo que va a ir allí?",
        it: "Che cosa direbbe a un amico che sta per andarci?",
        de: "Was würden Sie einem Freund sagen, der dorthin fährt?",
      },
    ],
  },
  {
    id: "c1-travel-02",
    domain: "travel",
    text: {
      en: "Have you ever felt like a foreigner somewhere? What was that experience like for you?",
      fr: "Vous êtes-vous déjà senti étranger quelque part ? Comment avez-vous vécu cette expérience ?",
      "nl-BE": "Hebt u zich ooit ergens een buitenstaander gevoeld? Hoe hebt u dat beleefd?",
      es: "¿Alguna vez se ha sentido extranjero en algún sitio? ¿Cómo vivió esa experiencia?",
      it: "Si è mai sentito straniero da qualche parte? Come ha vissuto quell'esperienza?",
      de: "Haben Sie sich schon einmal irgendwo fremd gefühlt? Wie haben Sie diese Erfahrung erlebt?",
    },
    simpler: {
      en: "Have you lived or travelled in another country? How was it?",
      fr: "Avez-vous vécu ou voyagé dans un autre pays ? C'était comment ?",
      "nl-BE": "Hebt u in een ander land gewoond of gereisd? Hoe was dat?",
      es: "¿Ha vivido o viajado en otro país? ¿Qué tal fue?",
      it: "Ha vissuto o viaggiato in un altro paese? Com'è stato?",
      de: "Haben Sie in einem anderen Land gelebt oder sind Sie dort gereist? Wie war das?",
    },
    followUps: [
      {
        en: "What helped you feel more at ease?",
        fr: "Qu'est-ce qui vous a aidé à vous sentir plus à l'aise ?",
        "nl-BE": "Wat hielp u om u meer op uw gemak te voelen?",
        es: "¿Qué le ayudó a sentirse más a gusto?",
        it: "Che cosa l'ha aiutata a sentirsi più a suo agio?",
        de: "Was hat Ihnen geholfen, sich wohler zu fühlen?",
      },
      {
        en: "What did it teach you about your own culture?",
        fr: "Qu'est-ce que cela vous a appris sur votre propre culture ?",
        "nl-BE": "Wat heeft het u geleerd over uw eigen cultuur?",
        es: "¿Qué le enseñó sobre su propia cultura?",
        it: "Che cosa le ha insegnato sulla sua cultura?",
        de: "Was hat Ihnen das über Ihre eigene Kultur gezeigt?",
      },
    ],
  },
  {
    id: "c1-tech-01",
    domain: "technology",
    text: {
      en: "How has the way you use your phone changed over the last few years, and how do you feel about that?",
      fr: "Comment votre façon d'utiliser votre téléphone a-t-elle changé ces dernières années, et qu'en pensez-vous ?",
      "nl-BE": "Hoe is de manier waarop u uw gsm gebruikt de laatste jaren veranderd, en wat vindt u daarvan?",
      es: "¿Cómo ha cambiado en los últimos años su manera de usar el móvil, y qué le parece?",
      it: "Com'è cambiato negli ultimi anni il suo modo di usare il telefono, e che cosa ne pensa?",
      de: "Wie hat sich Ihre Art, das Handy zu benutzen, in den letzten Jahren verändert, und wie finden Sie das?",
    },
    simpler: {
      en: "How do you use your phone? Do you use it too much?",
      fr: "Comment utilisez-vous votre téléphone ? Vous l'utilisez trop ?",
      "nl-BE": "Hoe gebruikt u uw gsm? Gebruikt u hem te veel?",
      es: "¿Cómo usa el móvil? ¿Lo usa demasiado?",
      it: "Come usa il telefono? Lo usa troppo?",
      de: "Wie benutzen Sie Ihr Handy? Benutzen Sie es zu viel?",
    },
    followUps: [
      {
        en: "Have you ever tried to use it less? How did it go?",
        fr: "Avez-vous déjà essayé de l'utiliser moins ? Comment ça s'est passé ?",
        "nl-BE": "Hebt u ooit geprobeerd hem minder te gebruiken? Hoe ging dat?",
        es: "¿Alguna vez ha intentado usarlo menos? ¿Cómo le fue?",
        it: "Ha mai provato a usarlo di meno? Com'è andata?",
        de: "Haben Sie schon einmal versucht, es weniger zu benutzen? Wie lief das?",
      },
      {
        en: "What would you miss most without it?",
        fr: "Qu'est-ce qui vous manquerait le plus sans lui ?",
        "nl-BE": "Wat zou u het meest missen zonder hem?",
        es: "¿Qué echaría más de menos sin él?",
        it: "Che cosa le mancherebbe di più senza?",
        de: "Was würden Sie ohne es am meisten vermissen?",
      },
    ],
  },
  {
    id: "c1-tech-02",
    domain: "technology",
    text: {
      en: "Tell me about something new — an app, a tool, a way of working — that took you a while to get used to. How did you adapt?",
      fr: "Parlez-moi d'une nouveauté — une application, un outil, une façon de travailler — à laquelle vous avez mis du temps à vous habituer. Comment vous êtes-vous adapté ?",
      "nl-BE": "Vertel eens over iets nieuws — een app, een toestel, een manier van werken — waaraan u even moest wennen. Hoe hebt u zich aangepast?",
      es: "Hábleme de algo nuevo — una aplicación, una herramienta, una forma de trabajar — a lo que le costó acostumbrarse. ¿Cómo se adaptó?",
      it: "Mi parli di una novità — un'app, uno strumento, un modo di lavorare — a cui ha impiegato del tempo ad abituarsi. Come si è adattato?",
      de: "Erzählen Sie mir von etwas Neuem — einer App, einem Werkzeug, einer Arbeitsweise —, an das Sie sich erst gewöhnen mussten. Wie haben Sie sich angepasst?",
    },
    simpler: {
      en: "Was a new app or tool difficult for you? Why?",
      fr: "Une nouvelle application ou un nouvel outil a-t-il été difficile pour vous ? Pourquoi ?",
      "nl-BE": "Was een nieuwe app of een nieuw toestel moeilijk voor u? Waarom?",
      es: "¿Le resultó difícil alguna aplicación o herramienta nueva? ¿Por qué?",
      it: "Un'app o uno strumento nuovo è stato difficile per lei? Perché?",
      de: "War eine neue App oder ein neues Gerät schwierig für Sie? Warum?",
    },
    followUps: [
      {
        en: "What finally made it click?",
        fr: "Qu'est-ce qui a fini par faire le déclic ?",
        "nl-BE": "Wat deed het uiteindelijk klikken?",
        es: "¿Qué hizo que al final le resultara fácil?",
        it: "Che cosa alla fine l'ha sbloccata?",
        de: "Was hat am Ende den Knoten gelöst?",
      },
      {
        en: "Do you usually adapt quickly to new things?",
        fr: "En général, vous adaptez-vous vite à la nouveauté ?",
        "nl-BE": "Past u zich meestal snel aan nieuwe dingen aan?",
        es: "¿Suele adaptarse rápido a las cosas nuevas?",
        it: "Di solito si adatta in fretta alle novità?",
        de: "Passen Sie sich normalerweise schnell an Neues an?",
      },
    ],
  },
  {
    id: "c1-other-01",
    domain: "opinions_other",
    text: {
      en: "Tell me about a piece of advice you were given that you only understood much later.",
      fr: "Parlez-moi d'un conseil qu'on vous a donné et que vous n'avez compris que bien plus tard.",
      "nl-BE": "Vertel eens over een raad die u ooit kreeg en die u pas veel later begreep.",
      es: "Hábleme de un consejo que le dieron y que no entendió hasta mucho después.",
      it: "Mi parli di un consiglio che le hanno dato e che ha capito solo molto più tardi.",
      de: "Erzählen Sie mir von einem Rat, den Sie bekommen und erst viel später verstanden haben.",
    },
    simpler: {
      en: "What is a good piece of advice someone gave you?",
      fr: "Quel bon conseil quelqu'un vous a-t-il donné ?",
      "nl-BE": "Welke goede raad heeft iemand u ooit gegeven?",
      es: "¿Qué buen consejo le dio alguien?",
      it: "Quale buon consiglio le ha dato qualcuno?",
      de: "Welchen guten Rat hat Ihnen jemand gegeben?",
    },
    followUps: [
      {
        en: "Why do you think it took so long to understand it?",
        fr: "Pourquoi, selon vous, avez-vous mis si longtemps à le comprendre ?",
        "nl-BE": "Waarom denkt u dat het zo lang duurde voor u het begreep?",
        es: "¿Por qué cree que tardó tanto en entenderlo?",
        it: "Perché secondo lei ci ha messo così tanto a capirlo?",
        de: "Warum hat es Ihrer Meinung nach so lange gedauert, bis Sie ihn verstanden haben?",
      },
      {
        en: "Have you passed it on to anyone?",
        fr: "L'avez-vous transmis à quelqu'un ?",
        "nl-BE": "Hebt u die raad aan iemand doorgegeven?",
        es: "¿Se lo ha transmitido a alguien?",
        it: "L'ha trasmesso a qualcuno?",
        de: "Haben Sie ihn an jemanden weitergegeben?",
      },
    ],
  },
  {
    id: "c1-other-02",
    domain: "opinions_other",
    text: {
      en: "What is something you have become better at with age, and how did that happen?",
      fr: "Dans quel domaine êtes-vous devenu meilleur avec l'âge, et comment est-ce arrivé ?",
      "nl-BE": "Waarin bent u met de jaren beter geworden, en hoe is dat gekomen?",
      es: "¿En qué se ha vuelto mejor con los años, y cómo ocurrió?",
      it: "In che cosa è migliorato con l'età, e come è successo?",
      de: "Worin sind Sie mit dem Alter besser geworden, und wie ist das gekommen?",
    },
    simpler: {
      en: "What do you do better now than before?",
      fr: "Qu'est-ce que vous faites mieux maintenant qu'avant ?",
      "nl-BE": "Wat doet u nu beter dan vroeger?",
      es: "¿Qué hace mejor ahora que antes?",
      it: "Che cosa fa meglio adesso rispetto a prima?",
      de: "Was machen Sie heute besser als früher?",
    },
    followUps: [
      {
        en: "Was there a moment when you noticed the change?",
        fr: "Y a-t-il eu un moment où vous avez remarqué ce changement ?",
        "nl-BE": "Was er een moment waarop u die verandering opmerkte?",
        es: "¿Hubo un momento en que notó el cambio?",
        it: "C'è stato un momento in cui ha notato il cambiamento?",
        de: "Gab es einen Moment, in dem Sie die Veränderung bemerkt haben?",
      },
      {
        en: "What are you still working on?",
        fr: "Sur quoi travaillez-vous encore ?",
        "nl-BE": "Waar werkt u nog aan?",
        es: "¿En qué sigue trabajando?",
        it: "Su che cosa sta ancora lavorando?",
        de: "Woran arbeiten Sie noch?",
      },
    ],
  },
];
