import type { BankEntry } from "@/lib/question-bank/types";

// C2 — nuance and reflection: how the speaker's own views and experience have
// shifted over time, subtle distinctions about themselves, self-aware
// qualification. Same rules as c1.ts (personal, no for/against, no role-play,
// no specialist knowledge) — a genuine step up from C1 comes from what a full
// answer has to hold together (contrast, time, self-analysis), not from a
// harder or more abstract task.
export const C2: BankEntry[] = [
  {
    id: "c2-home-01",
    domain: "home_city",
    text: {
      en: "Some people feel at home almost anywhere, others only in one place. Which are you, and where do you think that comes from?",
      fr: "Certaines personnes se sentent chez elles presque partout, d'autres dans un seul endroit. Et vous, et d'où cela vient-il selon vous ?",
      "nl-BE": "Sommige mensen voelen zich bijna overal thuis, anderen maar op één plek. Tot welke groep behoort u, en waar komt dat volgens u vandaan?",
      es: "Algunas personas se sienten en casa casi en cualquier sitio, otras solo en un lugar. ¿Y usted, y de dónde cree que viene eso?",
      it: "Alcune persone si sentono a casa quasi ovunque, altre in un solo posto. Lei come si sente, e da dove pensa che venga?",
      de: "Manche Menschen fühlen sich fast überall zu Hause, andere nur an einem Ort. Wie ist das bei Ihnen, und woher kommt das Ihrer Meinung nach?",
    },
    simpler: {
      en: "Do you feel at home quickly in a new place? Why?",
      fr: "Vous sentez-vous vite chez vous dans un nouvel endroit ? Pourquoi ?",
      "nl-BE": "Voelt u zich snel thuis op een nieuwe plek? Waarom?",
      es: "¿Se siente en casa rápido en un lugar nuevo? ¿Por qué?",
      it: "Si sente subito a casa in un posto nuovo? Perché?",
      de: "Fühlen Sie sich an einem neuen Ort schnell zu Hause? Warum?",
    },
    followUps: [
      {
        en: "Has that always been the case, or has it changed?",
        fr: "Est-ce que ça a toujours été le cas, ou cela a-t-il changé ?",
        "nl-BE": "Is dat altijd zo geweest, of is dat veranderd?",
        es: "¿Siempre ha sido así, o ha cambiado?",
        it: "È sempre stato così, o è cambiato?",
        de: "War das schon immer so, oder hat sich das verändert?",
      },
      {
        en: "What does that say about what really matters to you?",
        fr: "Qu'est-ce que cela dit de ce qui compte vraiment pour vous ?",
        "nl-BE": "Wat zegt dat over wat echt belangrijk voor u is?",
        es: "¿Qué dice eso de lo que de verdad le importa?",
        it: "Che cosa dice questo di ciò che conta davvero per lei?",
        de: "Was sagt das darüber, was Ihnen wirklich wichtig ist?",
      },
    ],
  },
  {
    id: "c2-home-02",
    domain: "home_city",
    text: {
      en: "If you looked at the place where you live through a newcomer's eyes, what would strike them that you no longer notice?",
      fr: "Si vous regardiez l'endroit où vous vivez avec les yeux d'un nouvel arrivant, qu'est-ce qui le frapperait et que vous ne remarquez plus ?",
      "nl-BE": "Als u de plek waar u woont bekeek door de ogen van een nieuwkomer, wat zou hem opvallen dat u zelf niet meer ziet?",
      es: "Si mirara el lugar donde vive con los ojos de alguien recién llegado, ¿qué le llamaría la atención que usted ya no nota?",
      it: "Se guardasse il posto in cui vive con gli occhi di un nuovo arrivato, che cosa lo colpirebbe che lei non nota più?",
      de: "Wenn Sie Ihren Wohnort mit den Augen eines Neuankömmlings sähen, was würde ihm auffallen, das Sie selbst nicht mehr bemerken?",
    },
    simpler: {
      en: "What would a visitor notice first where you live?",
      fr: "Qu'est-ce qu'un visiteur remarquerait en premier là où vous vivez ?",
      "nl-BE": "Wat zou een bezoeker het eerst opvallen waar u woont?",
      es: "¿Qué notaría primero un visitante donde vive usted?",
      it: "Che cosa noterebbe per prima cosa un visitatore dove vive lei?",
      de: "Was würde einem Besucher bei Ihnen zuerst auffallen?",
    },
    followUps: [
      {
        en: "When do you think you stopped noticing it?",
        fr: "À quel moment pensez-vous avoir cessé de le remarquer ?",
        "nl-BE": "Wanneer denkt u dat u het niet meer opmerkte?",
        es: "¿Cuándo cree que dejó de notarlo?",
        it: "Quando pensa di aver smesso di notarlo?",
        de: "Wann haben Sie Ihrer Meinung nach aufgehört, es zu bemerken?",
      },
      {
        en: "Is that something you're glad about, or does it bother you a little?",
        fr: "Est-ce que cela vous réjouit, ou est-ce que ça vous dérange un peu ?",
        "nl-BE": "Bent u daar blij om, of stoort het u een beetje?",
        es: "¿Eso le alegra, o le molesta un poco?",
        it: "È una cosa che le fa piacere, o la disturba un po'?",
        de: "Freut Sie das, oder stört es Sie ein wenig?",
      },
    ],
  },
  {
    id: "c2-family-01",
    domain: "family",
    text: {
      en: "Which values from your upbringing have you kept, and which have you consciously left behind? What made the difference?",
      fr: "Quelles valeurs de votre éducation avez-vous gardées, et lesquelles avez-vous consciemment laissées de côté ? Qu'est-ce qui a fait la différence ?",
      "nl-BE": "Welke waarden uit uw opvoeding hebt u behouden, en welke hebt u bewust achter u gelaten? Wat maakte het verschil?",
      es: "¿Qué valores de su educación ha conservado, y cuáles ha dejado atrás de forma consciente? ¿Qué marcó la diferencia?",
      it: "Quali valori della sua educazione ha conservato, e quali ha lasciato consapevolmente da parte? Che cosa ha fatto la differenza?",
      de: "Welche Werte aus Ihrer Erziehung haben Sie behalten, und welche haben Sie bewusst hinter sich gelassen? Was hat den Unterschied gemacht?",
    },
    simpler: {
      en: "What did you learn from your family that you still do today?",
      fr: "Qu'avez-vous appris de votre famille et que vous faites encore aujourd'hui ?",
      "nl-BE": "Wat hebt u van uw familie geleerd dat u vandaag nog doet?",
      es: "¿Qué aprendió de su familia que todavía hace hoy?",
      it: "Che cosa ha imparato dalla sua famiglia che fa ancora oggi?",
      de: "Was haben Sie von Ihrer Familie gelernt, das Sie heute noch tun?",
    },
    followUps: [
      {
        en: "Was that a clear decision, or more of a slow shift?",
        fr: "Était-ce une décision nette, ou plutôt une évolution lente ?",
        "nl-BE": "Was dat een duidelijke beslissing, of eerder een langzame verschuiving?",
        es: "¿Fue una decisión clara, o más bien un cambio lento?",
        it: "È stata una decisione netta, o piuttosto un'evoluzione lenta?",
        de: "War das eine klare Entscheidung oder eher eine langsame Entwicklung?",
      },
      {
        en: "How do the people close to you see those choices?",
        fr: "Comment vos proches perçoivent-ils ces choix ?",
        "nl-BE": "Hoe kijken de mensen rond u naar die keuzes?",
        es: "¿Cómo ven esas decisiones las personas cercanas a usted?",
        it: "Come vedono queste scelte le persone a lei vicine?",
        de: "Wie sehen die Menschen, die Ihnen nahestehen, diese Entscheidungen?",
      },
    ],
  },
  {
    id: "c2-family-02",
    domain: "family",
    text: {
      en: "How has your relationship with someone in your family changed as you have both grown older?",
      fr: "Comment votre relation avec un membre de votre famille a-t-elle évolué à mesure que vous avez vieilli tous les deux ?",
      "nl-BE": "Hoe is uw band met iemand uit uw familie veranderd naarmate u allebei ouder werd?",
      es: "¿Cómo ha cambiado su relación con alguien de su familia a medida que los dos se han hecho mayores?",
      it: "Com'è cambiato il suo rapporto con qualcuno della sua famiglia man mano che siete cresciuti entrambi?",
      de: "Wie hat sich Ihre Beziehung zu jemandem aus Ihrer Familie verändert, während Sie beide älter geworden sind?",
    },
    simpler: {
      en: "Who in your family are you close to? Has it always been like that?",
      fr: "De qui êtes-vous proche dans votre famille ? Ça a toujours été comme ça ?",
      "nl-BE": "Met wie in uw familie hebt u een goede band? Is dat altijd zo geweest?",
      es: "¿Con quién de su familia tiene más relación? ¿Siempre ha sido así?",
      it: "A chi è più legato nella sua famiglia? È sempre stato così?",
      de: "Wem in Ihrer Familie stehen Sie nahe? War das schon immer so?",
    },
    followUps: [
      {
        en: "What do you understand about them now that you didn't before?",
        fr: "Qu'est-ce que vous comprenez d'elle aujourd'hui que vous ne compreniez pas avant ?",
        "nl-BE": "Wat begrijpt u nu van die persoon dat u vroeger niet begreep?",
        es: "¿Qué entiende ahora de esa persona que antes no entendía?",
        it: "Che cosa capisce oggi di quella persona che prima non capiva?",
        de: "Was verstehen Sie heute an diesem Menschen, das Sie früher nicht verstanden haben?",
      },
      {
        en: "What do you think made the relationship change?",
        fr: "Qu'est-ce qui, selon vous, a fait évoluer cette relation ?",
        "nl-BE": "Wat heeft die band volgens u doen veranderen?",
        es: "¿Qué cree que hizo cambiar esa relación?",
        it: "Che cosa pensa abbia fatto cambiare quel rapporto?",
        de: "Was hat die Beziehung Ihrer Meinung nach verändert?",
      },
    ],
  },
  {
    id: "c2-work-01",
    domain: "work_studies",
    text: {
      en: "Looking back, which moment in your working life or studies taught you the most, even if it didn't feel that way at the time?",
      fr: "Avec le recul, quel moment de votre vie professionnelle ou de vos études vous a le plus appris, même si ce n'était pas l'impression que vous aviez sur le moment ?",
      "nl-BE": "Als u terugkijkt, welk moment in uw loopbaan of studie heeft u het meest geleerd, ook al voelde het toen niet zo?",
      es: "Mirando atrás, ¿qué momento de su vida laboral o de sus estudios le enseñó más, aunque en su momento no lo pareciera?",
      it: "Ripensandoci, quale momento della sua vita lavorativa o dei suoi studi le ha insegnato di più, anche se allora non sembrava?",
      de: "Rückblickend: Welcher Moment in Ihrem Berufsleben oder Studium hat Sie am meisten gelehrt, auch wenn es sich damals nicht so angefühlt hat?",
    },
    simpler: {
      en: "What was a difficult moment in your work or studies? What did you learn?",
      fr: "Quel a été un moment difficile dans votre travail ou vos études ? Qu'avez-vous appris ?",
      "nl-BE": "Wat was een moeilijk moment in uw werk of studie? Wat hebt u geleerd?",
      es: "¿Cuál fue un momento difícil en su trabajo o sus estudios? ¿Qué aprendió?",
      it: "Qual è stato un momento difficile nel suo lavoro o nei suoi studi? Che cosa ha imparato?",
      de: "Was war ein schwieriger Moment in Ihrer Arbeit oder Ihrem Studium? Was haben Sie gelernt?",
    },
    followUps: [
      {
        en: "How did you see it at the time, compared with now?",
        fr: "Comment le voyiez-vous à l'époque, par rapport à aujourd'hui ?",
        "nl-BE": "Hoe zag u het toen, in vergelijking met nu?",
        es: "¿Cómo lo veía entonces, comparado con ahora?",
        it: "Come lo vedeva allora, rispetto a oggi?",
        de: "Wie haben Sie es damals gesehen, im Vergleich zu heute?",
      },
      {
        en: "Would you want to go through it again, knowing what you know now?",
        fr: "Voudriez-vous le revivre, en sachant ce que vous savez maintenant ?",
        "nl-BE": "Zou u het opnieuw willen meemaken, met wat u nu weet?",
        es: "¿Querría volver a vivirlo, sabiendo lo que sabe ahora?",
        it: "Vorrebbe riviverlo, sapendo quello che sa adesso?",
        de: "Würden Sie es mit Ihrem heutigen Wissen noch einmal erleben wollen?",
      },
    ],
  },
  {
    id: "c2-work-02",
    domain: "work_studies",
    text: {
      en: "How would you describe the gap between how others see your work and how you see it yourself?",
      fr: "Comment décririez-vous l'écart entre la façon dont les autres voient votre travail et la façon dont vous le voyez vous-même ?",
      "nl-BE": "Hoe zou u het verschil beschrijven tussen hoe anderen uw werk zien en hoe u het zelf ziet?",
      es: "¿Cómo describiría la diferencia entre cómo ven los demás su trabajo y cómo lo ve usted?",
      it: "Come descriverebbe la distanza tra come gli altri vedono il suo lavoro e come lo vede lei?",
      de: "Wie würden Sie den Unterschied beschreiben zwischen dem, wie andere Ihre Arbeit sehen, und wie Sie sie selbst sehen?",
    },
    simpler: {
      en: "Do people understand what you do at work or in your studies?",
      fr: "Les gens comprennent-ils ce que vous faites dans votre travail ou vos études ?",
      "nl-BE": "Begrijpen mensen wat u doet in uw werk of studie?",
      es: "¿La gente entiende lo que hace en su trabajo o en sus estudios?",
      it: "Le persone capiscono che cosa fa nel suo lavoro o nei suoi studi?",
      de: "Verstehen die Leute, was Sie in Ihrer Arbeit oder im Studium machen?",
    },
    followUps: [
      {
        en: "Does that gap bother you, or not really?",
        fr: "Cet écart vous gêne-t-il, ou pas vraiment ?",
        "nl-BE": "Stoort dat verschil u, of eigenlijk niet?",
        es: "¿Le molesta esa diferencia, o no mucho?",
        it: "Questa distanza la disturba, o non molto?",
        de: "Stört Sie dieser Unterschied, oder eigentlich nicht?",
      },
      {
        en: "Has it ever led to a misunderstanding?",
        fr: "Cela a-t-il déjà provoqué un malentendu ?",
        "nl-BE": "Heeft dat ooit tot een misverstand geleid?",
        es: "¿Ha provocado alguna vez un malentendido?",
        it: "Ha mai causato un malinteso?",
        de: "Hat das schon einmal zu einem Missverständnis geführt?",
      },
    ],
  },
  {
    id: "c2-hobbies-01",
    domain: "hobbies_free_time",
    text: {
      en: "What does the way you spend your free time reveal about you that people might not guess?",
      fr: "Qu'est-ce que votre façon de passer votre temps libre révèle de vous que les gens ne devineraient peut-être pas ?",
      "nl-BE": "Wat zegt de manier waarop u uw vrije tijd doorbrengt over u, dat mensen misschien niet zouden raden?",
      es: "¿Qué revela de usted su manera de pasar el tiempo libre que la gente quizá no adivinaría?",
      it: "Che cosa rivela di lei il modo in cui passa il tempo libero, che le persone forse non immaginerebbero?",
      de: "Was verrät die Art, wie Sie Ihre Freizeit verbringen, über Sie, das andere vielleicht nicht vermuten würden?",
    },
    simpler: {
      en: "What does your free time say about you?",
      fr: "Qu'est-ce que votre temps libre dit de vous ?",
      "nl-BE": "Wat zegt uw vrije tijd over u?",
      es: "¿Qué dice de usted su tiempo libre?",
      it: "Che cosa dice di lei il suo tempo libero?",
      de: "Was sagt Ihre Freizeit über Sie aus?",
    },
    followUps: [
      {
        en: "Is that something you chose, or did it just happen?",
        fr: "Est-ce quelque chose que vous avez choisi, ou est-ce venu tout seul ?",
        "nl-BE": "Hebt u daarvoor gekozen, of is het gewoon zo gegroeid?",
        es: "¿Es algo que eligió, o surgió sin más?",
        it: "È una cosa che ha scelto, o è venuta da sé?",
        de: "Haben Sie sich das ausgesucht, oder hat es sich einfach so ergeben?",
      },
      {
        en: "Would the people who know you best agree?",
        fr: "Les personnes qui vous connaissent le mieux seraient-elles d'accord ?",
        "nl-BE": "Zouden de mensen die u het best kennen het daarmee eens zijn?",
        es: "¿Estarían de acuerdo las personas que mejor le conocen?",
        it: "Le persone che la conoscono meglio sarebbero d'accordo?",
        de: "Würden die Menschen, die Sie am besten kennen, dem zustimmen?",
      },
    ],
  },
  {
    id: "c2-hobbies-02",
    domain: "hobbies_free_time",
    text: {
      en: "Think of a book, a film or a song that meant something different to you at two moments of your life. What changed — the work, or you?",
      fr: "Pensez à un livre, un film ou une chanson qui a eu un sens différent pour vous à deux moments de votre vie. Qu'est-ce qui a changé — l'œuvre, ou vous ?",
      "nl-BE": "Denk aan een boek, een film of een lied dat op twee momenten in uw leven iets anders voor u betekende. Wat is er veranderd — het werk, of uzelf?",
      es: "Piense en un libro, una película o una canción que significó algo distinto para usted en dos momentos de su vida. ¿Qué cambió: la obra, o usted?",
      it: "Pensi a un libro, un film o una canzone che ha avuto un significato diverso per lei in due momenti della sua vita. Che cosa è cambiato: l'opera, o lei?",
      de: "Denken Sie an ein Buch, einen Film oder ein Lied, das Ihnen zu zwei Zeitpunkten Ihres Lebens etwas anderes bedeutet hat. Was hat sich verändert — das Werk oder Sie?",
    },
    simpler: {
      en: "Is there a book or a film you see differently today than before?",
      fr: "Y a-t-il un livre ou un film que vous voyez différemment aujourd'hui ?",
      "nl-BE": "Is er een boek of een film die u vandaag anders ziet dan vroeger?",
      es: "¿Hay algún libro o película que hoy vea de otra manera?",
      it: "C'è un libro o un film che oggi vede in modo diverso?",
      de: "Gibt es ein Buch oder einen Film, den Sie heute anders sehen als früher?",
    },
    followUps: [
      {
        en: "What does that tell you about who you were back then?",
        fr: "Qu'est-ce que cela vous dit de la personne que vous étiez à l'époque ?",
        "nl-BE": "Wat zegt dat over wie u toen was?",
        es: "¿Qué le dice eso de la persona que era entonces?",
        it: "Che cosa le dice di chi era allora?",
        de: "Was sagt Ihnen das darüber, wer Sie damals waren?",
      },
      {
        en: "Would you recommend it to someone younger? Why?",
        fr: "Le recommanderiez-vous à quelqu'un de plus jeune ? Pourquoi ?",
        "nl-BE": "Zou u het aanraden aan iemand die jonger is? Waarom?",
        es: "¿Se lo recomendaría a alguien más joven? ¿Por qué?",
        it: "Lo consiglierebbe a qualcuno più giovane? Perché?",
        de: "Würden Sie es jemand Jüngerem empfehlen? Warum?",
      },
    ],
  },
  {
    id: "c2-food-01",
    domain: "food_daily_life",
    text: {
      en: "Which small everyday routine matters to you far more than it probably should, and why do you think that is?",
      fr: "Quelle petite habitude du quotidien compte pour vous bien plus qu'elle ne le devrait sans doute, et pourquoi, à votre avis ?",
      "nl-BE": "Welke kleine dagelijkse gewoonte betekent veel meer voor u dan ze waarschijnlijk zou moeten, en waarom denkt u dat dat zo is?",
      es: "¿Qué pequeña rutina diaria le importa mucho más de lo que probablemente debería, y por qué cree que es así?",
      it: "Quale piccola abitudine quotidiana conta per lei molto più di quanto probabilmente dovrebbe, e perché secondo lei?",
      de: "Welche kleine Alltagsgewohnheit ist Ihnen viel wichtiger, als sie es vermutlich sein sollte, und woran liegt das Ihrer Meinung nach?",
    },
    simpler: {
      en: "Which small habit is important for you every day? Why?",
      fr: "Quelle petite habitude est importante pour vous chaque jour ? Pourquoi ?",
      "nl-BE": "Welke kleine gewoonte is elke dag belangrijk voor u? Waarom?",
      es: "¿Qué pequeña costumbre es importante para usted cada día? ¿Por qué?",
      it: "Quale piccola abitudine è importante per lei ogni giorno? Perché?",
      de: "Welche kleine Gewohnheit ist Ihnen jeden Tag wichtig? Warum?",
    },
    followUps: [
      {
        en: "What happens when you can't do it?",
        fr: "Que se passe-t-il quand vous ne pouvez pas la faire ?",
        "nl-BE": "Wat gebeurt er als u het niet kunt doen?",
        es: "¿Qué pasa cuando no puede hacerla?",
        it: "Che cosa succede quando non può farla?",
        de: "Was passiert, wenn Sie sie nicht machen können?",
      },
      {
        en: "Where do you think it comes from?",
        fr: "D'où vient-elle, à votre avis ?",
        "nl-BE": "Waar komt ze volgens u vandaan?",
        es: "¿De dónde cree que viene?",
        it: "Da dove pensa che venga?",
        de: "Woher kommt sie Ihrer Meinung nach?",
      },
    ],
  },
  {
    id: "c2-food-02",
    domain: "food_daily_life",
    text: {
      en: "What do the meals you share with others mean to you, beyond the food itself?",
      fr: "Que représentent pour vous les repas partagés avec d'autres, au-delà de ce qu'il y a dans l'assiette ?",
      "nl-BE": "Wat betekenen maaltijden die u met anderen deelt voor u, los van het eten zelf?",
      es: "¿Qué significan para usted las comidas que comparte con otros, más allá de la comida en sí?",
      it: "Che cosa rappresentano per lei i pasti condivisi con altri, al di là del cibo in sé?",
      de: "Was bedeuten Ihnen gemeinsame Mahlzeiten mit anderen, über das Essen selbst hinaus?",
    },
    simpler: {
      en: "Do you like eating with other people? Why?",
      fr: "Vous aimez manger avec d'autres personnes ? Pourquoi ?",
      "nl-BE": "Eet u graag samen met anderen? Waarom?",
      es: "¿Le gusta comer con otras personas? ¿Por qué?",
      it: "Le piace mangiare con altre persone? Perché?",
      de: "Essen Sie gern mit anderen zusammen? Warum?",
    },
    followUps: [
      {
        en: "Is there one meal you remember particularly well?",
        fr: "Y a-t-il un repas dont vous vous souvenez particulièrement ?",
        "nl-BE": "Is er een maaltijd die u zich bijzonder goed herinnert?",
        es: "¿Hay alguna comida que recuerde especialmente?",
        it: "C'è un pasto che ricorda in modo particolare?",
        de: "Gibt es eine Mahlzeit, an die Sie sich besonders gut erinnern?",
      },
      {
        en: "Has that meaning changed over the years?",
        fr: "Ce sens a-t-il changé avec les années ?",
        "nl-BE": "Is die betekenis in de loop der jaren veranderd?",
        es: "¿Ha cambiado ese significado con los años?",
        it: "Questo significato è cambiato con gli anni?",
        de: "Hat sich diese Bedeutung im Lauf der Jahre verändert?",
      },
    ],
  },
  {
    id: "c2-travel-01",
    domain: "travel",
    text: {
      en: "Is there a trip or a stay abroad that changed something lasting in the way you see things? What exactly?",
      fr: "Y a-t-il un voyage ou un séjour à l'étranger qui a changé durablement votre façon de voir les choses ? Quoi exactement ?",
      "nl-BE": "Is er een reis of een verblijf in het buitenland dat blijvend iets veranderd heeft aan hoe u de dingen ziet? Wat precies?",
      es: "¿Hay algún viaje o estancia en el extranjero que cambiara de forma duradera su manera de ver las cosas? ¿Qué exactamente?",
      it: "C'è un viaggio o un soggiorno all'estero che ha cambiato in modo duraturo il suo modo di vedere le cose? Che cosa esattamente?",
      de: "Gibt es eine Reise oder einen Auslandsaufenthalt, der Ihre Sicht auf die Dinge dauerhaft verändert hat? Was genau?",
    },
    simpler: {
      en: "Did a trip change you? How?",
      fr: "Un voyage vous a-t-il changé ? Comment ?",
      "nl-BE": "Heeft een reis u veranderd? Hoe?",
      es: "¿Le cambió algún viaje? ¿Cómo?",
      it: "Un viaggio l'ha cambiata? Come?",
      de: "Hat eine Reise Sie verändert? Wie?",
    },
    followUps: [
      {
        en: "Did you notice it at the time, or only later?",
        fr: "L'avez-vous remarqué sur le moment, ou seulement plus tard ?",
        "nl-BE": "Merkte u dat meteen, of pas later?",
        es: "¿Lo notó en ese momento, o solo más tarde?",
        it: "Se n'è accorto subito, o solo più tardi?",
        de: "Haben Sie es sofort gemerkt oder erst später?",
      },
      {
        en: "What was hardest to explain to the people back home?",
        fr: "Qu'est-ce qui a été le plus difficile à expliquer à vos proches en rentrant ?",
        "nl-BE": "Wat was het moeilijkst om uit te leggen aan de mensen thuis?",
        es: "¿Qué fue lo más difícil de explicar a la gente al volver?",
        it: "Che cosa è stato più difficile spiegare alle persone a casa?",
        de: "Was war am schwierigsten, den Leuten zu Hause zu erklären?",
      },
    ],
  },
  {
    id: "c2-travel-02",
    domain: "travel",
    text: {
      en: "When you travel, how much do you try to blend in, and how much do you accept being a visitor? Why?",
      fr: "En voyage, jusqu'où essayez-vous de vous fondre dans le décor, et jusqu'où acceptez-vous d'être un visiteur ? Pourquoi ?",
      "nl-BE": "Als u reist, in hoeverre probeert u op te gaan in de omgeving, en in hoeverre aanvaardt u dat u een bezoeker bent? Waarom?",
      es: "Cuando viaja, ¿hasta qué punto intenta integrarse, y hasta qué punto acepta ser un visitante? ¿Por qué?",
      it: "Quando viaggia, fino a che punto cerca di confondersi con la gente del posto, e fino a che punto accetta di essere un visitatore? Perché?",
      de: "Wie sehr versuchen Sie auf Reisen, nicht aufzufallen, und wie sehr akzeptieren Sie, Besucher zu sein? Warum?",
    },
    simpler: {
      en: "When you travel, do you try to live like the local people?",
      fr: "En voyage, essayez-vous de vivre comme les gens du pays ?",
      "nl-BE": "Probeert u op reis te leven zoals de mensen daar?",
      es: "Cuando viaja, ¿intenta vivir como la gente del lugar?",
      it: "Quando viaggia, cerca di vivere come la gente del posto?",
      de: "Versuchen Sie auf Reisen, wie die Einheimischen zu leben?",
    },
    followUps: [
      {
        en: "Has that ever led to an awkward moment?",
        fr: "Cela a-t-il déjà donné lieu à un moment gênant ?",
        "nl-BE": "Heeft dat ooit tot een ongemakkelijk moment geleid?",
        es: "¿Ha dado lugar alguna vez a un momento incómodo?",
        it: "Ha mai portato a un momento imbarazzante?",
        de: "Hat das schon einmal zu einer peinlichen Situation geführt?",
      },
      {
        en: "Has your approach changed as you have travelled more?",
        fr: "Votre approche a-t-elle changé au fil de vos voyages ?",
        "nl-BE": "Is uw aanpak veranderd naarmate u meer reisde?",
        es: "¿Ha cambiado su manera de hacerlo a medida que ha viajado más?",
        it: "Il suo approccio è cambiato man mano che ha viaggiato di più?",
        de: "Hat sich Ihre Haltung verändert, je mehr Sie gereist sind?",
      },
    ],
  },
  {
    id: "c2-tech-01",
    domain: "technology",
    text: {
      en: "What has technology made easier in your life that you now suspect was worth doing the hard way?",
      fr: "Qu'est-ce que la technologie a rendu plus facile dans votre vie et qui, vous le soupçonnez aujourd'hui, valait la peine d'être fait à l'ancienne ?",
      "nl-BE": "Wat heeft technologie in uw leven makkelijker gemaakt, terwijl u nu vermoedt dat het de moeite waard was om het op de moeilijke manier te doen?",
      es: "¿Qué le ha facilitado la tecnología en su vida que ahora sospecha que valía la pena hacer a la antigua?",
      it: "Che cosa la tecnologia ha reso più facile nella sua vita che ora sospetta valesse la pena fare alla vecchia maniera?",
      de: "Was hat Ihnen die Technik im Leben leichter gemacht, bei dem Sie inzwischen vermuten, dass sich der mühsame Weg gelohnt hätte?",
    },
    simpler: {
      en: "What does technology make easier for you? Is that always a good thing?",
      fr: "Qu'est-ce que la technologie vous facilite ? Est-ce toujours une bonne chose ?",
      "nl-BE": "Wat maakt technologie makkelijker voor u? Is dat altijd goed?",
      es: "¿Qué le facilita la tecnología? ¿Es siempre algo bueno?",
      it: "Che cosa le rende più facile la tecnologia? È sempre una buona cosa?",
      de: "Was macht Ihnen die Technik leichter? Ist das immer gut?",
    },
    followUps: [
      {
        en: "Have you ever gone back to doing it the old way?",
        fr: "Vous est-il arrivé de revenir à l'ancienne méthode ?",
        "nl-BE": "Bent u ooit teruggegaan naar de oude manier?",
        es: "¿Alguna vez ha vuelto a hacerlo a la antigua?",
        it: "Le è mai capitato di tornare al vecchio modo?",
        de: "Sind Sie schon einmal zur alten Methode zurückgekehrt?",
      },
      {
        en: "What made you notice it?",
        fr: "Qu'est-ce qui vous l'a fait remarquer ?",
        "nl-BE": "Waardoor bent u dat gaan opmerken?",
        es: "¿Qué le hizo darse cuenta?",
        it: "Che cosa gliel'ha fatto notare?",
        de: "Wodurch ist Ihnen das aufgefallen?",
      },
    ],
  },
  {
    id: "c2-tech-02",
    domain: "technology",
    text: {
      en: "How do you decide what you share about yourself online and what you keep private? Has that line moved over time?",
      fr: "Comment décidez-vous de ce que vous partagez de vous en ligne et de ce que vous gardez pour vous ? Cette limite a-t-elle bougé avec le temps ?",
      "nl-BE": "Hoe beslist u wat u online over uzelf deelt en wat u privé houdt? Is die grens in de loop der tijd verschoven?",
      es: "¿Cómo decide lo que comparte de usted en internet y lo que guarda para sí? ¿Se ha movido ese límite con el tiempo?",
      it: "Come decide che cosa condividere di sé online e che cosa tenere per sé? Questo limite si è spostato nel tempo?",
      de: "Wie entscheiden Sie, was Sie online von sich teilen und was Sie für sich behalten? Hat sich diese Grenze mit der Zeit verschoben?",
    },
    simpler: {
      en: "What do you share online, and what do you keep private?",
      fr: "Qu'est-ce que vous partagez en ligne, et qu'est-ce que vous gardez pour vous ?",
      "nl-BE": "Wat deelt u online, en wat houdt u voor uzelf?",
      es: "¿Qué comparte en internet, y qué guarda para usted?",
      it: "Che cosa condivide online, e che cosa tiene per sé?",
      de: "Was teilen Sie online, und was behalten Sie für sich?",
    },
    followUps: [
      {
        en: "What made that line move?",
        fr: "Qu'est-ce qui a fait bouger cette limite ?",
        "nl-BE": "Waardoor is die grens verschoven?",
        es: "¿Qué hizo que ese límite se moviera?",
        it: "Che cosa ha fatto spostare questo limite?",
        de: "Wodurch hat sich diese Grenze verschoben?",
      },
      {
        en: "Do the people around you draw the line in the same place?",
        fr: "Les gens autour de vous placent-ils la limite au même endroit ?",
        "nl-BE": "Leggen de mensen rond u die grens op dezelfde plek?",
        es: "¿Las personas de su entorno ponen el límite en el mismo sitio?",
        it: "Le persone intorno a lei mettono il limite nello stesso punto?",
        de: "Ziehen die Menschen um Sie herum die Grenze an derselben Stelle?",
      },
    ],
  },
  {
    id: "c2-other-01",
    domain: "opinions_other",
    text: {
      en: "Think of an opinion you held strongly ten years ago and see differently today. What actually changed your mind?",
      fr: "Pensez à une opinion que vous défendiez fermement il y a dix ans et que vous voyez autrement aujourd'hui. Qu'est-ce qui vous a réellement fait changer d'avis ?",
      "nl-BE": "Denk aan een mening die u tien jaar geleden sterk verdedigde en die u vandaag anders ziet. Wat heeft u eigenlijk van gedachten doen veranderen?",
      es: "Piense en una opinión que defendía con firmeza hace diez años y que hoy ve de otra manera. ¿Qué le hizo cambiar de opinión realmente?",
      it: "Pensi a un'opinione che sosteneva con convinzione dieci anni fa e che oggi vede in modo diverso. Che cosa le ha fatto davvero cambiare idea?",
      de: "Denken Sie an eine Meinung, die Sie vor zehn Jahren fest vertreten haben und heute anders sehen. Was hat Sie tatsächlich umdenken lassen?",
    },
    simpler: {
      en: "Is there an idea you had before and don't have now? Why?",
      fr: "Y a-t-il une idée que vous aviez avant et que vous n'avez plus ? Pourquoi ?",
      "nl-BE": "Is er een idee dat u vroeger had en nu niet meer? Waarom?",
      es: "¿Hay alguna idea que tenía antes y ya no tiene? ¿Por qué?",
      it: "C'è un'idea che aveva prima e che ora non ha più? Perché?",
      de: "Gibt es eine Idee, die Sie früher hatten und heute nicht mehr? Warum?",
    },
    followUps: [
      {
        en: "Was it one event, or a slow shift?",
        fr: "Était-ce un événement précis, ou une évolution lente ?",
        "nl-BE": "Was het één gebeurtenis, of een langzame verschuiving?",
        es: "¿Fue un hecho concreto, o un cambio lento?",
        it: "È stato un evento preciso, o un cambiamento lento?",
        de: "War es ein bestimmtes Ereignis oder eine langsame Entwicklung?",
      },
      {
        en: "Is there anything from your old view that you still hold on to?",
        fr: "Y a-t-il quelque chose de votre ancienne opinion que vous gardez encore ?",
        "nl-BE": "Is er iets van uw vroegere mening dat u nog altijd vasthoudt?",
        es: "¿Hay algo de su antigua opinión que todavía conserve?",
        it: "C'è qualcosa della sua vecchia opinione che conserva ancora?",
        de: "Gibt es etwas von Ihrer früheren Meinung, an dem Sie noch festhalten?",
      },
    ],
  },
  {
    id: "c2-other-02",
    domain: "opinions_other",
    text: {
      en: "What is a quality you admire in others but find hard to practise yourself? Why do you think that is?",
      fr: "Quelle qualité admirez-vous chez les autres mais avez-vous du mal à mettre en pratique vous-même ? Pourquoi, à votre avis ?",
      "nl-BE": "Welke eigenschap bewondert u bij anderen, maar vindt u zelf moeilijk om in de praktijk te brengen? Waarom denkt u dat dat zo is?",
      es: "¿Qué cualidad admira en los demás pero le cuesta poner en práctica? ¿Por qué cree que es así?",
      it: "Quale qualità ammira negli altri ma fa fatica a mettere in pratica lei stesso? Perché secondo lei?",
      de: "Welche Eigenschaft bewundern Sie bei anderen, fällt Ihnen selbst aber schwer? Woran liegt das Ihrer Meinung nach?",
    },
    simpler: {
      en: "What quality do you admire in other people?",
      fr: "Quelle qualité admirez-vous chez les autres ?",
      "nl-BE": "Welke eigenschap bewondert u bij andere mensen?",
      es: "¿Qué cualidad admira en otras personas?",
      it: "Quale qualità ammira nelle altre persone?",
      de: "Welche Eigenschaft bewundern Sie bei anderen Menschen?",
    },
    followUps: [
      {
        en: "Have you ever tried to develop it? What happened?",
        fr: "Avez-vous déjà essayé de la développer ? Que s'est-il passé ?",
        "nl-BE": "Hebt u ooit geprobeerd die te ontwikkelen? Wat gebeurde er?",
        es: "¿Alguna vez ha intentado desarrollarla? ¿Qué pasó?",
        it: "Ha mai provato a svilupparla? Che cosa è successo?",
        de: "Haben Sie schon einmal versucht, sie zu entwickeln? Was ist passiert?",
      },
      {
        en: "Is there a situation where it would have made a real difference?",
        fr: "Y a-t-il une situation où elle aurait vraiment fait la différence ?",
        "nl-BE": "Is er een situatie waarin die eigenschap echt een verschil had gemaakt?",
        es: "¿Hay alguna situación en la que habría marcado una verdadera diferencia?",
        it: "C'è una situazione in cui avrebbe fatto davvero la differenza?",
        de: "Gibt es eine Situation, in der sie wirklich einen Unterschied gemacht hätte?",
      },
    ],
  },
];
